// Auto-generated by generate_side_db.py from XX0_EVENT.SB7 side-quest ICB reverse-engineering.
// Do not edit manually. Regenerate: python DAT/maps/generate_side_db.py
using System;
using System.Collections.Generic;

namespace TOAHEX
{
    public static class SideQuestJumpDatabase
    {
        public class SideEntry
        {
            public string name;
            public int page;
            public string quest_name;   // 聚合任务名（如"凯的奥义书"，去掉 n/m 后缀）
            public int quest_step;      // 当前步骤 n（0=非多步任务）
            public int quest_total;     // 总步骤 m（0=非多步任务）
            public uint event_id;
            public uint map_id;
            public float x;
            public float y;
            public float z;
            public float angle;
            public List<int> set_flags = new List<int>();
            public List<int> clear_flags = new List<int>();
            public int complete_flag;  // 完成标志 flag 号（0=无独立完成标志）
            public override string ToString() { return name; }
        }

        private static Dictionary<int, List<SideEntry>> _entries = new Dictionary<int, List<SideEntry>>();

        static SideQuestJumpDatabase()
        {
            InitInlineData();
        }

        public static IEnumerable<int> GetPages()
        {
            foreach (var k in _entries.Keys) yield return k;
        }

        public static List<SideEntry> GetEntries(int page)
            => _entries.TryGetValue(page, out var list) ? list : null;

        public static int EntryCount
        {
            get { int n = 0; foreach (var kv in _entries) n += kv.Value.Count; return n; }
        }

        private static void InitInlineData()
        {
            {
                var list = new List<SideEntry>();
                list.Add(new SideEntry { name = "新手教程　CC符", page = 1, quest_name = "新手教程　CC符", quest_step = 0, quest_total = 0, event_id = 1003130u, map_id = 427u, x = 287f, y = 5f, z = -168f, angle = 130f, set_flags = new List<int>{}, clear_flags = new List<int>{}, complete_flag = 0 });
                list.Add(new SideEntry { name = "缪火焰习得", page = 1, quest_name = "缪火焰习得", quest_step = 0, quest_total = 0, event_id = 1003120u, map_id = 425u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{}, clear_flags = new List<int>{1501}, complete_flag = 0 });
                list.Add(new SideEntry { name = "缪火焰使用", page = 1, quest_name = "缪火焰使用", quest_step = 0, quest_total = 0, event_id = 1003120u, map_id = 424u, x = -373f, y = 399f, z = -2729f, angle = 110f, set_flags = new List<int>{}, clear_flags = new List<int>{}, complete_flag = 0 });
                list.Add(new SideEntry { name = "取回装备　塔尔塔洛斯", page = 1, quest_name = "取回装备　塔尔塔洛斯", quest_step = 0, quest_total = 0, event_id = 1004080u, map_id = 497u, x = -98f, y = 0f, z = 467f, angle = 26f, set_flags = new List<int>{}, clear_flags = new List<int>{}, complete_flag = 0 });
                list.Add(new SideEntry { name = "电梯停运了　塔尔塔洛斯", page = 1, quest_name = "电梯停运了　塔尔塔洛斯", quest_step = 0, quest_total = 0, event_id = 1004080u, map_id = 495u, x = 3f, y = 0f, z = 2500f, angle = 0f, set_flags = new List<int>{}, clear_flags = new List<int>{1507}, complete_flag = 0 });
                list.Add(new SideEntry { name = "推拉的说明　塔尔塔洛斯", page = 1, quest_name = "推拉的说明　塔尔塔洛斯", quest_step = 0, quest_total = 0, event_id = 1004090u, map_id = 498u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{}, clear_flags = new List<int>{}, complete_flag = 0 });
                list.Add(new SideEntry { name = "炸穿舰壁逃出　塔尔塔洛斯", page = 1, quest_name = "炸穿舰壁逃出　塔尔塔洛斯", quest_step = 0, quest_total = 0, event_id = 1004100u, map_id = 498u, x = -242f, y = 0f, z = -76f, angle = 270f, set_flags = new List<int>{}, clear_flags = new List<int>{}, complete_flag = 0 });
                list.Add(new SideEntry { name = "战斗新手教程　FOF", page = 1, quest_name = "战斗新手教程　FOF", quest_step = 0, quest_total = 0, event_id = 1005110u, map_id = 462u, x = -523f, y = -183f, z = 2099f, angle = 0f, set_flags = new List<int>{}, clear_flags = new List<int>{2008}, complete_flag = 0 });
                list.Add(new SideEntry { name = "森特比纳大树", page = 1, quest_name = "森特比纳大树", quest_step = 0, quest_total = 0, event_id = 1001000u, map_id = 466u, x = 3189f, y = 1179f, z = -3042f, angle = 235f, set_flags = new List<int>{1002}, clear_flags = new List<int>{1500}, complete_flag = 0 });
                _entries[1] = list;
            }
            {
                var list = new List<SideEntry>();
                list.Add(new SideEntry { name = "战斗新手教程　意外", page = 2, quest_name = "战斗新手教程　意外", quest_step = 0, quest_total = 0, event_id = 1006030u, map_id = 107u, x = 0f, y = 10f, z = -280f, angle = 180f, set_flags = new List<int>{}, clear_flags = new List<int>{}, complete_flag = 0 });
                list.Add(new SideEntry { name = "新手教程　FS嵌石", page = 2, quest_name = "新手教程　FS嵌石", quest_step = 0, quest_total = 0, event_id = 1009060u, map_id = 69u, x = 1030f, y = 541f, z = -957f, angle = 0f, set_flags = new List<int>{}, clear_flags = new List<int>{2009}, complete_flag = 0 });
                list.Add(new SideEntry { name = "娜塔莉亚角色出场　废工厂途中", page = 2, quest_name = "娜塔莉亚角色出场　废工厂途中", quest_step = 0, quest_total = 0, event_id = 1010010u, map_id = 69u, x = 1030f, y = 541f, z = -957f, angle = 0f, set_flags = new List<int>{}, clear_flags = new List<int>{1508}, complete_flag = 0 });
                list.Add(new SideEntry { name = "缪撞击习得", page = 2, quest_name = "缪撞击习得", quest_step = 0, quest_total = 0, event_id = 1010060u, map_id = 477u, x = -151f, y = -699f, z = 6309f, angle = 0f, set_flags = new List<int>{1000}, clear_flags = new List<int>{}, complete_flag = 0 });
                list.Add(new SideEntry { name = "缪撞击使用", page = 2, quest_name = "缪撞击使用", quest_step = 0, quest_total = 0, event_id = 1010070u, map_id = 477u, x = -2307f, y = 451f, z = 2997f, angle = 0f, set_flags = new List<int>{1000}, clear_flags = new List<int>{1502,237}, complete_flag = 0 });
                list.Add(new SideEntry { name = "在山顶累倒的伊昂", page = 2, quest_name = "在山顶累倒的伊昂", quest_step = 0, quest_total = 0, event_id = 1011110u, map_id = 417u, x = 318f, y = 41f, z = -297f, angle = 180f, set_flags = new List<int>{}, clear_flags = new List<int>{1509}, complete_flag = 0 });
                list.Add(new SideEntry { name = "ｂｏｓｓ伏笔　瓦云镜窟", page = 2, quest_name = "ｂｏｓｓ伏笔　瓦云镜窟", quest_step = 0, quest_total = 0, event_id = 2015000u, map_id = 408u, x = -905f, y = 2f, z = 1635f, angle = 200f, set_flags = new List<int>{}, clear_flags = new List<int>{1510}, complete_flag = 0 });
                list.Add(new SideEntry { name = "赌场", page = 2, quest_name = "赌场", quest_step = 0, quest_total = 0, event_id = 0u, map_id = 519u, x = -400f, y = 190f, z = 1128f, angle = 180f, set_flags = new List<int>{}, clear_flags = new List<int>{1260}, complete_flag = 0 });
                list.Add(new SideEntry { name = "怀疑阿修　扎奥遗迹", page = 2, quest_name = "怀疑阿修　扎奥遗迹", quest_step = 0, quest_total = 0, event_id = 3025030u, map_id = 475u, x = 1359f, y = 2815f, z = 730f, angle = 180f, set_flags = new List<int>{}, clear_flags = new List<int>{1511}, complete_flag = 0 });
                _entries[2] = list;
            }
            {
                var list = new List<SideEntry>();
                list.Add(new SideEntry { name = "ｂｏｓｓ伏笔　扎奥遗迹", page = 3, quest_name = "ｂｏｓｓ伏笔　扎奥遗迹", quest_step = 0, quest_total = 0, event_id = 3025030u, map_id = 478u, x = -52f, y = 15f, z = -776f, angle = 180f, set_flags = new List<int>{}, clear_flags = new List<int>{1512}, complete_flag = 0 });
                list.Add(new SideEntry { name = "对外壳大地的想法　扎奥遗迹", page = 3, quest_name = "对外壳大地的想法　扎奥遗迹", quest_step = 0, quest_total = 0, event_id = 3025050u, map_id = 480u, x = 2337f, y = 54f, z = 24f, angle = 0f, set_flags = new List<int>{}, clear_flags = new List<int>{1512}, complete_flag = 0 });
                list.Add(new SideEntry { name = "缪飞天习得", page = 3, quest_name = "缪飞天习得", quest_step = 0, quest_total = 0, event_id = 0u, map_id = 304u, x = 1334f, y = -600f, z = -546f, angle = 90f, set_flags = new List<int>{}, clear_flags = new List<int>{}, complete_flag = 0 });
                list.Add(new SideEntry { name = "缪飞天使用", page = 3, quest_name = "缪飞天使用", quest_step = 0, quest_total = 0, event_id = 0u, map_id = 304u, x = 1012f, y = -600f, z = -901f, angle = 100f, set_flags = new List<int>{}, clear_flags = new List<int>{1503}, complete_flag = 0 });
                list.Add(new SideEntry { name = "莱纳探索中", page = 3, quest_name = "莱纳探索中", quest_step = 0, quest_total = 0, event_id = 3030100u, map_id = 122u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{}, clear_flags = new List<int>{1514}, complete_flag = 0 });
                list.Add(new SideEntry { name = "娜塔莉亚支线事件　梵蒂卡尔", page = 3, quest_name = "娜塔莉亚支线事件　梵蒂卡尔", quest_step = 0, quest_total = 0, event_id = 3030040u, map_id = 69u, x = 1986f, y = 541f, z = -81f, angle = 200f, set_flags = new List<int>{}, clear_flags = new List<int>{1515}, complete_flag = 0 });
                list.Add(new SideEntry { name = "魔物退治", page = 3, quest_name = "魔物退治", quest_step = 0, quest_total = 0, event_id = 4034000u, map_id = 59u, x = 785f, y = 0f, z = -1011f, angle = 42f, set_flags = new List<int>{}, clear_flags = new List<int>{1516,1517,1518,1519,1289,1290,1291,1292,1293,1294,1295}, complete_flag = 0 });
                list.Add(new SideEntry { name = "谒见厅支线事件", page = 3, quest_name = "谒见厅支线事件", quest_step = 0, quest_total = 0, event_id = 3030170u, map_id = 597u, x = 785f, y = 0f, z = -1011f, angle = 42f, set_flags = new List<int>{}, clear_flags = new List<int>{1520}, complete_flag = 0 });
                list.Add(new SideEntry { name = "回忆阿修的事件", page = 3, quest_name = "回忆阿修的事件", quest_step = 0, quest_total = 0, event_id = 3031280u, map_id = 408u, x = -905f, y = 2f, z = 1657f, angle = 15f, set_flags = new List<int>{}, clear_flags = new List<int>{1521}, complete_flag = 0 });
                _entries[3] = list;
            }
            {
                var list = new List<SideEntry>();
                list.Add(new SideEntry { name = "平衡调整　扎雷霍火山", page = 4, quest_name = "平衡调整　扎雷霍火山", quest_step = 0, quest_total = 0, event_id = 3031240u, map_id = 268u, x = 2828f, y = 271f, z = -243f, angle = 323f, set_flags = new List<int>{}, clear_flags = new List<int>{1522}, complete_flag = 0 });
                list.Add(new SideEntry { name = "伙伴分割①（卢克＆缇娅）", page = 4, quest_name = "伙伴分割①（卢克＆缇娅）", quest_step = 0, quest_total = 0, event_id = 3033030u, map_id = 560u, x = 0f, y = 4f, z = 5176f, angle = 180f, set_flags = new List<int>{}, clear_flags = new List<int>{1542}, complete_flag = 0 });
                list.Add(new SideEntry { name = "伙伴分割②（杰德＆阿尼丝）", page = 4, quest_name = "伙伴分割②（杰德＆阿尼丝）", quest_step = 0, quest_total = 0, event_id = 3033030u, map_id = 563u, x = 0f, y = 9f, z = -1425f, angle = 0f, set_flags = new List<int>{}, clear_flags = new List<int>{1543}, complete_flag = 0 });
                list.Add(new SideEntry { name = "伙伴分割③（凯＆娜塔莉亚）", page = 4, quest_name = "伙伴分割③（凯＆娜塔莉亚）", quest_step = 0, quest_total = 0, event_id = 3033030u, map_id = 561u, x = 0f, y = -6260f, z = 628f, angle = 0f, set_flags = new List<int>{}, clear_flags = new List<int>{1544}, complete_flag = 0 });
                list.Add(new SideEntry { name = "城市的起源　梵蒂卡尔", page = 4, quest_name = "城市的起源　梵蒂卡尔", quest_step = 0, quest_total = 0, event_id = 4034000u, map_id = 102u, x = 982f, y = 0f, z = -3f, angle = 270f, set_flags = new List<int>{}, clear_flags = new List<int>{1523}, complete_flag = 0 });
                list.Add(new SideEntry { name = "城市的起源　尤利亚城", page = 4, quest_name = "城市的起源　尤利亚城", quest_step = 0, quest_total = 0, event_id = 4034000u, map_id = 620u, x = 237f, y = 0f, z = -419f, angle = 130f, set_flags = new List<int>{}, clear_flags = new List<int>{1524}, complete_flag = 0 });
                list.Add(new SideEntry { name = "火箭塔事件", page = 4, quest_name = "火箭塔事件", quest_step = 0, quest_total = 0, event_id = 4034000u, map_id = 375u, x = 2711f, y = 2765f, z = -2805f, angle = 180f, set_flags = new List<int>{}, clear_flags = new List<int>{1545}, complete_flag = 0 });
                list.Add(new SideEntry { name = "复制品控制室事件", page = 4, quest_name = "复制品控制室事件", quest_step = 0, quest_total = 0, event_id = 4034000u, map_id = 457u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{}, clear_flags = new List<int>{1546}, complete_flag = 0 });
                list.Add(new SideEntry { name = "进入火山", page = 4, quest_name = "进入火山", quest_step = 0, quest_total = 0, event_id = 4035110u, map_id = 261u, x = -134f, y = -142f, z = 203f, angle = 0f, set_flags = new List<int>{}, clear_flags = new List<int>{1547}, complete_flag = 0 });
                _entries[4] = list;
            }
            {
                var list = new List<SideEntry>();
                list.Add(new SideEntry { name = "缪火焰ver2习得", page = 5, quest_name = "缪火焰ver2习得", quest_step = 0, quest_total = 0, event_id = 0u, map_id = 268u, x = 667f, y = -1f, z = -524f, angle = 308f, set_flags = new List<int>{}, clear_flags = new List<int>{}, complete_flag = 0 });
                list.Add(new SideEntry { name = "缪火焰ver2使用", page = 5, quest_name = "缪火焰ver2使用", quest_step = 0, quest_total = 0, event_id = 0u, map_id = 268u, x = -474f, y = -1f, z = -1063f, angle = 190f, set_flags = new List<int>{}, clear_flags = new List<int>{}, complete_flag = 0 });
                list.Add(new SideEntry { name = "有关阿莉埃塔的魔物", page = 5, quest_name = "有关阿莉埃塔的魔物", quest_step = 0, quest_total = 0, event_id = 0u, map_id = 0u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{}, clear_flags = new List<int>{}, complete_flag = 0 });
                list.Add(new SideEntry { name = "有关类似的建筑", page = 5, quest_name = "有关类似的建筑", quest_step = 0, quest_total = 0, event_id = 4036200u, map_id = 34u, x = -236f, y = 1400f, z = -1691f, angle = 270f, set_flags = new List<int>{}, clear_flags = new List<int>{1578}, complete_flag = 0 });
                list.Add(new SideEntry { name = "有关变成废墟的城市", page = 5, quest_name = "有关变成废墟的城市", quest_step = 0, quest_total = 0, event_id = 4036200u, map_id = 32u, x = -2597f, y = 700f, z = -4150f, angle = 90f, set_flags = new List<int>{}, clear_flags = new List<int>{1579}, complete_flag = 0 });
                list.Add(new SideEntry { name = "城市的起源　南梦宫岛", page = 5, quest_name = "城市的起源　南梦宫岛", quest_step = 0, quest_total = 0, event_id = 0u, map_id = 429u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{}, clear_flags = new List<int>{1580}, complete_flag = 0 });
                list.Add(new SideEntry { name = "监视室事件", page = 5, quest_name = "监视室事件", quest_step = 0, quest_total = 0, event_id = 0u, map_id = 432u, x = 768f, y = 0f, z = -27f, angle = 225f, set_flags = new List<int>{}, clear_flags = new List<int>{1581}, complete_flag = 0 });
                list.Add(new SideEntry { name = "漆黑之翼最终事件？", page = 5, quest_name = "漆黑之翼最终事件？", quest_step = 0, quest_total = 0, event_id = 0u, map_id = 433u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{1439}, clear_flags = new List<int>{1582}, complete_flag = 1439 });
                list.Add(new SideEntry { name = "行星气旋", page = 5, quest_name = "行星气旋", quest_step = 0, quest_total = 0, event_id = 4038150u, map_id = 554u, x = 0f, y = 10f, z = 0f, angle = 0f, set_flags = new List<int>{1335}, clear_flags = new List<int>{1588}, complete_flag = 1335 });
                _entries[5] = list;
            }
            {
                var list = new List<SideEntry>();
                list.Add(new SideEntry { name = "猜娜塔莉亚在哪", page = 6, quest_name = "猜娜塔莉亚在哪", quest_step = 0, quest_total = 0, event_id = 4038150u, map_id = 565u, x = 0f, y = 4f, z = -2013f, angle = 180f, set_flags = new List<int>{}, clear_flags = new List<int>{1589}, complete_flag = 0 });
                list.Add(new SideEntry { name = "阿修的足跡", page = 6, quest_name = "阿修的足跡", quest_step = 0, quest_total = 0, event_id = 4038270u, map_id = 437u, x = -100f, y = 6f, z = 1119f, angle = 180f, set_flags = new List<int>{}, clear_flags = new List<int>{1590}, complete_flag = 0 });
                list.Add(new SideEntry { name = "巨大的艾尔德兰特", page = 6, quest_name = "巨大的艾尔德兰特", quest_step = 0, quest_total = 0, event_id = 4039110u, map_id = 354u, x = 3026f, y = 15f, z = -240f, angle = 0f, set_flags = new List<int>{}, clear_flags = new List<int>{1591}, complete_flag = 0 });
                list.Add(new SideEntry { name = "复制品霍德", page = 6, quest_name = "复制品霍德", quest_step = 0, quest_total = 0, event_id = 4039150u, map_id = 362u, x = 27f, y = -2759f, z = -7583f, angle = 180f, set_flags = new List<int>{}, clear_flags = new List<int>{1592}, complete_flag = 0 });
                list.Add(new SideEntry { name = "在尤利亚墓前", page = 6, quest_name = "在尤利亚墓前", quest_step = 0, quest_total = 0, event_id = 4039190u, map_id = 367u, x = 0f, y = -20f, z = -305f, angle = 180f, set_flags = new List<int>{}, clear_flags = new List<int>{1593}, complete_flag = 0 });
                list.Add(new SideEntry { name = "缇娅的谱歌习得1/5", page = 6, quest_name = "缇娅的谱歌习得", quest_step = 1, quest_total = 5, event_id = 1005120u, map_id = 66u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{}, clear_flags = new List<int>{1599}, complete_flag = 0 });
                list.Add(new SideEntry { name = "缇娅的谱歌习得2/5", page = 6, quest_name = "缇娅的谱歌习得", quest_step = 2, quest_total = 5, event_id = 0u, map_id = 615u, x = 0f, y = 580f, z = -1709f, angle = 180f, set_flags = new List<int>{1599}, clear_flags = new List<int>{1600}, complete_flag = 1599 });
                list.Add(new SideEntry { name = "缇娅的谱歌习得3/5", page = 6, quest_name = "缇娅的谱歌习得", quest_step = 3, quest_total = 5, event_id = 0u, map_id = 616u, x = -66f, y = 0f, z = -350f, angle = 90f, set_flags = new List<int>{1600}, clear_flags = new List<int>{1601}, complete_flag = 1600 });
                list.Add(new SideEntry { name = "缇娅的谱歌习得4/5", page = 6, quest_name = "缇娅的谱歌习得", quest_step = 4, quest_total = 5, event_id = 4037999u, map_id = 147u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{1601}, clear_flags = new List<int>{1602}, complete_flag = 1601 });
                _entries[6] = list;
            }
            {
                var list = new List<SideEntry>();
                list.Add(new SideEntry { name = "缇娅的谱歌习得5/5", page = 7, quest_name = "缇娅的谱歌习得", quest_step = 5, quest_total = 5, event_id = 4037999u, map_id = 142u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{1635,1602}, clear_flags = new List<int>{1603}, complete_flag = 1602 });
                list.Add(new SideEntry { name = "内比利姆1/20 chu", page = 7, quest_name = "内比利姆1/20 chu", quest_step = 0, quest_total = 0, event_id = 4039999u, map_id = 142u, x = -72f, y = 167f, z = -1260f, angle = 30f, set_flags = new List<int>{}, clear_flags = new List<int>{1623,1642}, complete_flag = 0 });
                list.Add(new SideEntry { name = "内比利姆2/20 sno", page = 7, quest_name = "内比利姆2/20 sno", quest_step = 0, quest_total = 0, event_id = 4034000u, map_id = 544u, x = 73f, y = 0f, z = -264f, angle = 300f, set_flags = new List<int>{1623}, clear_flags = new List<int>{1624}, complete_flag = 1623 });
                list.Add(new SideEntry { name = "内比利姆3/20 wat", page = 7, quest_name = "内比利姆3/20 wat", quest_step = 0, quest_total = 0, event_id = 2021050u, map_id = 596u, x = -83f, y = 0f, z = 325f, angle = 80f, set_flags = new List<int>{1624}, clear_flags = new List<int>{1637,1625}, complete_flag = 1624 });
                list.Add(new SideEntry { name = "内比利姆4/20 wat", page = 7, quest_name = "内比利姆4/20 wat", quest_step = 0, quest_total = 0, event_id = 2021050u, map_id = 607u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{1625}, clear_flags = new List<int>{1626}, complete_flag = 0 });
                list.Add(new SideEntry { name = "内比利姆5/20 sco", page = 7, quest_name = "内比利姆5/20 sco", quest_step = 0, quest_total = 0, event_id = 4034000u, map_id = 485u, x = 1407f, y = 0f, z = 557f, angle = 90f, set_flags = new List<int>{1625}, clear_flags = new List<int>{1627}, complete_flag = 0 });
                list.Add(new SideEntry { name = "内比利姆6/20 sco", page = 7, quest_name = "内比利姆6/20 sco", quest_step = 0, quest_total = 0, event_id = 4034000u, map_id = 486u, x = -22f, y = 0f, z = -1065f, angle = 211f, set_flags = new List<int>{1625,1627}, clear_flags = new List<int>{1628}, complete_flag = 1627 });
                list.Add(new SideEntry { name = "内比利姆7/20 sco", page = 7, quest_name = "内比利姆7/20 sco", quest_step = 0, quest_total = 0, event_id = 4034000u, map_id = 486u, x = -22f, y = 0f, z = -1065f, angle = 211f, set_flags = new List<int>{1625,1627,1628,1629}, clear_flags = new List<int>{1630}, complete_flag = 1629 });
                list.Add(new SideEntry { name = "内比利姆8/20 las", page = 7, quest_name = "内比利姆8/20 las", quest_step = 0, quest_total = 0, event_id = 0u, map_id = 367u, x = 0f, y = -20f, z = -360f, angle = 180f, set_flags = new List<int>{1625}, clear_flags = new List<int>{1631}, complete_flag = 0 });
                _entries[7] = list;
            }
            {
                var list = new List<SideEntry>();
                list.Add(new SideEntry { name = "内比利姆9/20 exe", page = 8, quest_name = "内比利姆9/20 exe", quest_step = 0, quest_total = 0, event_id = 0u, map_id = 255u, x = 557f, y = 2003f, z = -2323f, angle = 90f, set_flags = new List<int>{1625}, clear_flags = new List<int>{1632}, complete_flag = 0 });
                list.Add(new SideEntry { name = "内比利姆10/20 chu", page = 8, quest_name = "内比利姆10/20 chu", quest_step = 0, quest_total = 0, event_id = 4038260u, map_id = 141u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{1625}, clear_flags = new List<int>{1633}, complete_flag = 0 });
                list.Add(new SideEntry { name = "内比利姆11/20 chu", page = 8, quest_name = "内比利姆11/20 chu", quest_step = 0, quest_total = 0, event_id = 4038230u, map_id = 181u, x = -94f, y = 0f, z = 176f, angle = 150f, set_flags = new List<int>{1633}, clear_flags = new List<int>{1634}, complete_flag = 1633 });
                list.Add(new SideEntry { name = "内比利姆12/20 chu", page = 8, quest_name = "内比利姆12/20 chu", quest_step = 0, quest_total = 0, event_id = 4037999u, map_id = 142u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{1634}, clear_flags = new List<int>{1635}, complete_flag = 1634 });
                list.Add(new SideEntry { name = "内比利姆13/20 各地图", page = 8, quest_name = "内比利姆13/20 各地图", quest_step = 0, quest_total = 0, event_id = 0u, map_id = 0u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{}, clear_flags = new List<int>{}, complete_flag = 0 });
                list.Add(new SideEntry { name = "内比利姆14/20 nev 战斗", page = 8, quest_name = "内比利姆14/20 nev 战斗", quest_step = 0, quest_total = 0, event_id = 4038230u, map_id = 435u, x = 83f, y = 4f, z = -1092f, angle = 180f, set_flags = new List<int>{1636}, clear_flags = new List<int>{1637}, complete_flag = 1636 });
                list.Add(new SideEntry { name = "内比利姆15/20 wat", page = 8, quest_name = "内比利姆15/20 wat", quest_step = 0, quest_total = 0, event_id = 4038230u, map_id = 596u, x = -83f, y = 0f, z = 325f, angle = 80f, set_flags = new List<int>{1637}, clear_flags = new List<int>{1638}, complete_flag = 1637 });
                list.Add(new SideEntry { name = "内比利姆16/20 ice 回想", page = 8, quest_name = "内比利姆16/20 ice 回想", quest_step = 0, quest_total = 0, event_id = 4039999u, map_id = 332u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{1638}, clear_flags = new List<int>{1639}, complete_flag = 1638 });
                list.Add(new SideEntry { name = "内比利姆17/20 wat", page = 8, quest_name = "内比利姆17/20 wat", quest_step = 0, quest_total = 0, event_id = 2021050u, map_id = 596u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{1639}, clear_flags = new List<int>{1640}, complete_flag = 1639 });
                _entries[8] = list;
            }
            {
                var list = new List<SideEntry>();
                list.Add(new SideEntry { name = "内比利姆18/20 wat", page = 9, quest_name = "内比利姆18/20 wat", quest_step = 0, quest_total = 0, event_id = 4037999u, map_id = 582u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{1640}, clear_flags = new List<int>{1641}, complete_flag = 1640 });
                list.Add(new SideEntry { name = "内比利姆19/20 wat", page = 9, quest_name = "内比利姆19/20 wat", quest_step = 0, quest_total = 0, event_id = 4037999u, map_id = 604u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{1641}, clear_flags = new List<int>{1642}, complete_flag = 1641 });
                list.Add(new SideEntry { name = "内比利姆20/20 chu", page = 9, quest_name = "内比利姆20/20 chu", quest_step = 0, quest_total = 0, event_id = 4039999u, map_id = 142u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{1642}, clear_flags = new List<int>{1643}, complete_flag = 1642 });
                list.Add(new SideEntry { name = "二周目奖励1/2", page = 9, quest_name = "二周目奖励", quest_step = 1, quest_total = 2, event_id = 1001030u, map_id = 103u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{}, clear_flags = new List<int>{}, complete_flag = 0 });
                list.Add(new SideEntry { name = "二周目奖励2/2", page = 9, quest_name = "二周目奖励", quest_step = 2, quest_total = 2, event_id = 2015999u, map_id = 621u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{}, clear_flags = new List<int>{}, complete_flag = 0 });
                list.Add(new SideEntry { name = "丽格蕾特的日记1/4", page = 9, quest_name = "丽格蕾特的日记", quest_step = 1, quest_total = 4, event_id = 4039200u, map_id = 622u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{1242}, clear_flags = new List<int>{1647}, complete_flag = 1242 });
                list.Add(new SideEntry { name = "丽格蕾特的日记2/4", page = 9, quest_name = "丽格蕾特的日记", quest_step = 2, quest_total = 4, event_id = 4039200u, map_id = 611u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{1647}, clear_flags = new List<int>{1648}, complete_flag = 1647 });
                list.Add(new SideEntry { name = "丽格蕾特的日记3/4", page = 9, quest_name = "丽格蕾特的日记", quest_step = 3, quest_total = 4, event_id = 4039200u, map_id = 622u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{1648}, clear_flags = new List<int>{1649}, complete_flag = 1648 });
                list.Add(new SideEntry { name = "丽格蕾特的日记4/4", page = 9, quest_name = "丽格蕾特的日记", quest_step = 4, quest_total = 4, event_id = 4039200u, map_id = 621u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{1649}, clear_flags = new List<int>{1650}, complete_flag = 1649 });
                _entries[9] = list;
            }
            {
                var list = new List<SideEntry>();
                list.Add(new SideEntry { name = "附身", page = 10, quest_name = "附身", quest_step = 0, quest_total = 0, event_id = 1001000u, map_id = 102u, x = 1489f, y = 0f, z = -60f, angle = 90f, set_flags = new List<int>{}, clear_flags = new List<int>{1525}, complete_flag = 0 });
                list.Add(new SideEntry { name = "料理新手教程", page = 10, quest_name = "料理新手教程", quest_step = 0, quest_total = 0, event_id = 1001000u, map_id = 65u, x = 240f, y = 0f, z = 173f, angle = 90f, set_flags = new List<int>{}, clear_flags = new List<int>{1526,1527}, complete_flag = 0 });
                list.Add(new SideEntry { name = "秘密的小箱1/2", page = 10, quest_name = "秘密的小箱", quest_step = 1, quest_total = 2, event_id = 1003040u, map_id = 59u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{}, clear_flags = new List<int>{1540,1541}, complete_flag = 0 });
                list.Add(new SideEntry { name = "秘密的小箱2/2", page = 10, quest_name = "秘密的小箱", quest_step = 2, quest_total = 2, event_id = 1003040u, map_id = 59u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{1540}, clear_flags = new List<int>{}, complete_flag = 1540 });
                list.Add(new SideEntry { name = "地图探索", page = 10, quest_name = "地图探索", quest_step = 0, quest_total = 0, event_id = 1001000u, map_id = 472u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{}, clear_flags = new List<int>{1529,1442}, complete_flag = 0 });
                list.Add(new SideEntry { name = "诺瓦尔粉丝俱乐部1/2", page = 10, quest_name = "诺瓦尔粉丝俱乐部", quest_step = 1, quest_total = 2, event_id = 1005100u, map_id = 466u, x = 425f, y = 0f, z = -163f, angle = 140f, set_flags = new List<int>{}, clear_flags = new List<int>{1530,1724,1725,1726}, complete_flag = 0 });
                list.Add(new SideEntry { name = "诺瓦尔粉丝俱乐部2/2", page = 10, quest_name = "诺瓦尔粉丝俱乐部", quest_step = 2, quest_total = 2, event_id = 1007060u, map_id = 215u, x = -1223f, y = 0f, z = 1543f, angle = 180f, set_flags = new List<int>{1530}, clear_flags = new List<int>{1724}, complete_flag = 1530 });
                list.Add(new SideEntry { name = "克塞多尼亚流通", page = 10, quest_name = "克塞多尼亚流通", quest_step = 0, quest_total = 0, event_id = 1001000u, map_id = 212u, x = -255f, y = 0f, z = 1506f, angle = 190f, set_flags = new List<int>{}, clear_flags = new List<int>{1531}, complete_flag = 0 });
                list.Add(new SideEntry { name = "尤利亚城流通1", page = 10, quest_name = "尤利亚城流通1", quest_step = 0, quest_total = 0, event_id = 2014000u, map_id = 612u, x = -1899f, y = 2f, z = -1715f, angle = 239f, set_flags = new List<int>{}, clear_flags = new List<int>{1532,1443}, complete_flag = 0 });
                _entries[10] = list;
            }
            {
                var list = new List<SideEntry>();
                list.Add(new SideEntry { name = "尤利亚城流通2", page = 11, quest_name = "尤利亚城流通2", quest_step = 0, quest_total = 0, event_id = 2016000u, map_id = 612u, x = -1899f, y = 2f, z = -1715f, angle = 239f, set_flags = new List<int>{}, clear_flags = new List<int>{1533,1444}, complete_flag = 0 });
                list.Add(new SideEntry { name = "尤利亚城流通3", page = 11, quest_name = "尤利亚城流通3", quest_step = 0, quest_total = 0, event_id = 2023000u, map_id = 612u, x = -1899f, y = 2f, z = -1715f, angle = 239f, set_flags = new List<int>{}, clear_flags = new List<int>{1534,1445}, complete_flag = 0 });
                list.Add(new SideEntry { name = "仓库番1", page = 11, quest_name = "仓库番1", quest_step = 0, quest_total = 0, event_id = 2018000u, map_id = 548u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{}, clear_flags = new List<int>{419,1535,1446}, complete_flag = 0 });
                list.Add(new SideEntry { name = "仓库番2", page = 11, quest_name = "仓库番2", quest_step = 0, quest_total = 0, event_id = 0u, map_id = 591u, x = -194f, y = 0f, z = -279f, angle = 180f, set_flags = new List<int>{}, clear_flags = new List<int>{417,1447,1536}, complete_flag = 0 });
                list.Add(new SideEntry { name = "仓库番3", page = 11, quest_name = "仓库番3", quest_step = 0, quest_total = 0, event_id = 2018000u, map_id = 460u, x = -733f, y = 21f, z = -649f, angle = 185f, set_flags = new List<int>{}, clear_flags = new List<int>{1449,1537,420}, complete_flag = 0 });
                list.Add(new SideEntry { name = "仓库番4", page = 11, quest_name = "仓库番4", quest_step = 0, quest_total = 0, event_id = 2018000u, map_id = 396u, x = -610f, y = 2f, z = -175f, angle = 180f, set_flags = new List<int>{}, clear_flags = new List<int>{418,1450,1538}, complete_flag = 0 });
                list.Add(new SideEntry { name = "仓库番5　1/4", page = 11, quest_name = "仓库番5", quest_step = 1, quest_total = 4, event_id = 2018000u, map_id = 548u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{421,422,424}, clear_flags = new List<int>{419,1535,1446}, complete_flag = 424 });
                list.Add(new SideEntry { name = "仓库番5　2/4", page = 11, quest_name = "仓库番5", quest_step = 2, quest_total = 4, event_id = 0u, map_id = 591u, x = -194f, y = 0f, z = -279f, angle = 180f, set_flags = new List<int>{422,423,424}, clear_flags = new List<int>{417,1447,1536}, complete_flag = 424 });
                list.Add(new SideEntry { name = "仓库番5　3/4", page = 11, quest_name = "仓库番5", quest_step = 3, quest_total = 4, event_id = 2018000u, map_id = 460u, x = -733f, y = 21f, z = -649f, angle = 185f, set_flags = new List<int>{421,422,423}, clear_flags = new List<int>{1449,1537,420}, complete_flag = 423 });
                _entries[11] = list;
            }
            {
                var list = new List<SideEntry>();
                list.Add(new SideEntry { name = "仓库番5　4/4", page = 12, quest_name = "仓库番5", quest_step = 4, quest_total = 4, event_id = 2018000u, map_id = 396u, x = -610f, y = 2f, z = -175f, angle = 180f, set_flags = new List<int>{421,423,424}, clear_flags = new List<int>{418,1450,1538}, complete_flag = 424 });
                list.Add(new SideEntry { name = "八音盒発動", page = 12, quest_name = "八音盒発動", quest_step = 0, quest_total = 0, event_id = 0u, map_id = 139u, x = -632f, y = 176f, z = 228f, angle = 270f, set_flags = new List<int>{}, clear_flags = new List<int>{1548}, complete_flag = 0 });
                list.Add(new SideEntry { name = "八音盒1", page = 12, quest_name = "八音盒1", quest_step = 0, quest_total = 0, event_id = 0u, map_id = 375u, x = 509f, y = 224f, z = -1551f, angle = 180f, set_flags = new List<int>{1548}, clear_flags = new List<int>{1554}, complete_flag = 0 });
                list.Add(new SideEntry { name = "八音盒2", page = 12, quest_name = "八音盒2", quest_step = 0, quest_total = 0, event_id = 0u, map_id = 579u, x = -1429f, y = 10f, z = -3400f, angle = 250f, set_flags = new List<int>{1548}, clear_flags = new List<int>{1550}, complete_flag = 0 });
                list.Add(new SideEntry { name = "八音盒3", page = 12, quest_name = "八音盒3", quest_step = 0, quest_total = 0, event_id = 0u, map_id = 115u, x = 0f, y = 5f, z = 200f, angle = 180f, set_flags = new List<int>{1620,1621,1548}, clear_flags = new List<int>{1551}, complete_flag = 1621 });
                list.Add(new SideEntry { name = "八音盒4", page = 12, quest_name = "八音盒4", quest_step = 0, quest_total = 0, event_id = 1001000u, map_id = 432u, x = -914f, y = 5f, z = -483f, angle = 200f, set_flags = new List<int>{1549}, clear_flags = new List<int>{1552}, complete_flag = 1549 });
                list.Add(new SideEntry { name = "八音盒5", page = 12, quest_name = "八音盒5", quest_step = 0, quest_total = 0, event_id = 4039050u, map_id = 215u, x = -754f, y = 5f, z = 2193f, angle = 180f, set_flags = new List<int>{1550,1551,1552}, clear_flags = new List<int>{1553}, complete_flag = 1552 });
                list.Add(new SideEntry { name = "鼓风机1", page = 12, quest_name = "鼓风机1", quest_step = 0, quest_total = 0, event_id = 2021000u, map_id = 379u, x = 37f, y = 0f, z = -76f, angle = 270f, set_flags = new List<int>{1000}, clear_flags = new List<int>{1556,1557,1558}, complete_flag = 0 });
                list.Add(new SideEntry { name = "鼓风机2", page = 12, quest_name = "鼓风机2", quest_step = 0, quest_total = 0, event_id = 3029000u, map_id = 379u, x = 37f, y = 0f, z = -76f, angle = 270f, set_flags = new List<int>{1000,1556}, clear_flags = new List<int>{1557,1558}, complete_flag = 1556 });
                _entries[12] = list;
            }
            {
                var list = new List<SideEntry>();
                list.Add(new SideEntry { name = "鼓风机3", page = 13, quest_name = "鼓风机3", quest_step = 0, quest_total = 0, event_id = 4035000u, map_id = 379u, x = 37f, y = 0f, z = -76f, angle = 270f, set_flags = new List<int>{1000,1556,1557}, clear_flags = new List<int>{1558}, complete_flag = 1557 });
                list.Add(new SideEntry { name = "迷宫房屋1", page = 13, quest_name = "迷宫房屋1", quest_step = 0, quest_total = 0, event_id = 4034000u, map_id = 514u, x = 1478f, y = 1f, z = -1214f, angle = 140f, set_flags = new List<int>{1000}, clear_flags = new List<int>{1608,1609,1610}, complete_flag = 0 });
                list.Add(new SideEntry { name = "迷宫房屋2", page = 13, quest_name = "迷宫房屋2", quest_step = 0, quest_total = 0, event_id = 4034000u, map_id = 514u, x = 1478f, y = 1f, z = -1214f, angle = 140f, set_flags = new List<int>{1000,1608}, clear_flags = new List<int>{1609,1610}, complete_flag = 0 });
                list.Add(new SideEntry { name = "迷宫房屋3", page = 13, quest_name = "迷宫房屋3", quest_step = 0, quest_total = 0, event_id = 4034000u, map_id = 514u, x = 1478f, y = 1f, z = -1214f, angle = 140f, set_flags = new List<int>{1000,1608,1609}, clear_flags = new List<int>{1610}, complete_flag = 1609 });
                list.Add(new SideEntry { name = "迷宫房屋4", page = 13, quest_name = "迷宫房屋4", quest_step = 0, quest_total = 0, event_id = 4034000u, map_id = 514u, x = 1478f, y = 1f, z = -1214f, angle = 140f, set_flags = new List<int>{1000,1608,1609,1610}, clear_flags = new List<int>{}, complete_flag = 1610 });
                list.Add(new SideEntry { name = "配膳1/2", page = 13, quest_name = "配膳", quest_step = 1, quest_total = 2, event_id = 2018000u, map_id = 532u, x = 345f, y = 0f, z = 566f, angle = 245f, set_flags = new List<int>{1000}, clear_flags = new List<int>{1564,1565}, complete_flag = 0 });
                list.Add(new SideEntry { name = "配膳2/2", page = 13, quest_name = "配膳", quest_step = 2, quest_total = 2, event_id = 3030000u, map_id = 532u, x = 345f, y = 0f, z = 566f, angle = 245f, set_flags = new List<int>{1000,1564,1565,501}, clear_flags = new List<int>{503}, complete_flag = 501 });
                list.Add(new SideEntry { name = "蚁狮1", page = 13, quest_name = "蚁狮1", quest_step = 0, quest_total = 0, event_id = 1001000u, map_id = 212u, x = 1708f, y = 0f, z = 739f, angle = 84f, set_flags = new List<int>{}, clear_flags = new List<int>{1559,1463,1560,1464,1465,1561,1466,1562,1563,1468,1469}, complete_flag = 0 });
                list.Add(new SideEntry { name = "蚁狮2", page = 13, quest_name = "蚁狮2", quest_step = 0, quest_total = 0, event_id = 1011000u, map_id = 212u, x = 1708f, y = 0f, z = 739f, angle = 84f, set_flags = new List<int>{1463}, clear_flags = new List<int>{1560,1464,1465,1561,1466,1562,1563,1468,1469}, complete_flag = 0 });
                _entries[13] = list;
            }
            {
                var list = new List<SideEntry>();
                list.Add(new SideEntry { name = "蚁狮3", page = 14, quest_name = "蚁狮3", quest_step = 0, quest_total = 0, event_id = 3024000u, map_id = 212u, x = 1708f, y = 0f, z = 739f, angle = 84f, set_flags = new List<int>{1463}, clear_flags = new List<int>{1465,1561,1466,1562,1563,1468,1469}, complete_flag = 0 });
                list.Add(new SideEntry { name = "蚁狮4", page = 14, quest_name = "蚁狮4", quest_step = 0, quest_total = 0, event_id = 3033000u, map_id = 212u, x = 1708f, y = 0f, z = 739f, angle = 84f, set_flags = new List<int>{1463}, clear_flags = new List<int>{1466,1562,1563,1468,1469}, complete_flag = 0 });
                list.Add(new SideEntry { name = "蚁狮5　1/2", page = 14, quest_name = "蚁狮5", quest_step = 1, quest_total = 2, event_id = 3033000u, map_id = 212u, x = 1708f, y = 0f, z = 739f, angle = 84f, set_flags = new List<int>{1562}, clear_flags = new List<int>{1563,1468,1469}, complete_flag = 1562 });
                list.Add(new SideEntry { name = "蚁狮5　2/2", page = 14, quest_name = "蚁狮5", quest_step = 2, quest_total = 2, event_id = 0u, map_id = 0u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{}, clear_flags = new List<int>{}, complete_flag = 0 });
                list.Add(new SideEntry { name = "斗技场再开", page = 14, quest_name = "斗技场再开", quest_step = 0, quest_total = 0, event_id = 4034000u, map_id = 528u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{}, clear_flags = new List<int>{1566}, complete_flag = 0 });
                list.Add(new SideEntry { name = "破坏桶", page = 14, quest_name = "破坏桶", quest_step = 0, quest_total = 0, event_id = 4034000u, map_id = 374u, x = 1300f, y = 5f, z = -152f, angle = 90f, set_flags = new List<int>{1000,1567}, clear_flags = new List<int>{}, complete_flag = 1567 });
                list.Add(new SideEntry { name = "料理1a　「徒步移动」选择后在地图发生", page = 14, quest_name = "料理1a　「徒步移动」选择后在地图发生", quest_step = 0, quest_total = 0, event_id = 1002140u, map_id = 504u, x = 1421f, y = -2337f, z = -1939f, angle = 0f, set_flags = new List<int>{}, clear_flags = new List<int>{1655}, complete_flag = 0 });
                list.Add(new SideEntry { name = "料理1b", page = 14, quest_name = "料理1b", quest_step = 0, quest_total = 0, event_id = 1003010u, map_id = 60u, x = -1341f, y = 15f, z = -875f, angle = 153f, set_flags = new List<int>{1001}, clear_flags = new List<int>{1651}, complete_flag = 0 });
                list.Add(new SideEntry { name = "料理5", page = 14, quest_name = "料理5", quest_step = 0, quest_total = 0, event_id = 1009999u, map_id = 82u, x = -6f, y = 0f, z = -259f, angle = 180f, set_flags = new List<int>{}, clear_flags = new List<int>{1652}, complete_flag = 0 });
                _entries[14] = list;
            }
            {
                var list = new List<SideEntry>();
                list.Add(new SideEntry { name = "料理7", page = 15, quest_name = "料理7", quest_step = 0, quest_total = 0, event_id = 4035070u, map_id = 139u, x = 498f, y = 0f, z = -1753f, angle = 117f, set_flags = new List<int>{}, clear_flags = new List<int>{1654}, complete_flag = 0 });
                list.Add(new SideEntry { name = "料理9", page = 15, quest_name = "料理9", quest_step = 0, quest_total = 0, event_id = 2019000u, map_id = 591u, x = 201f, y = 0f, z = 1f, angle = 155f, set_flags = new List<int>{}, clear_flags = new List<int>{1559}, complete_flag = 0 });
                list.Add(new SideEntry { name = "料理10", page = 15, quest_name = "料理10", quest_step = 0, quest_total = 0, event_id = 0u, map_id = 443u, x = -970f, y = -14f, z = 1958f, angle = 0f, set_flags = new List<int>{}, clear_flags = new List<int>{1656}, complete_flag = 0 });
                list.Add(new SideEntry { name = "料理11", page = 15, quest_name = "料理11", quest_step = 0, quest_total = 0, event_id = 3029040u, map_id = 300u, x = -64f, y = 106f, z = -485f, angle = 180f, set_flags = new List<int>{}, clear_flags = new List<int>{1657}, complete_flag = 0 });
                list.Add(new SideEntry { name = "料理12", page = 15, quest_name = "料理12", quest_step = 0, quest_total = 0, event_id = 3029040u, map_id = 458u, x = -276f, y = 2f, z = -407f, angle = 130f, set_flags = new List<int>{}, clear_flags = new List<int>{1658}, complete_flag = 0 });
                list.Add(new SideEntry { name = "料理19", page = 15, quest_name = "料理19", quest_step = 0, quest_total = 0, event_id = 4038230u, map_id = 147u, x = -671f, y = 0f, z = 36f, angle = 140f, set_flags = new List<int>{}, clear_flags = new List<int>{1659}, complete_flag = 0 });
                list.Add(new SideEntry { name = "料理20　1/2", page = 15, quest_name = "料理20", quest_step = 1, quest_total = 2, event_id = 4038230u, map_id = 98u, x = -347f, y = 50f, z = -10f, angle = 180f, set_flags = new List<int>{1702,1703}, clear_flags = new List<int>{1660,1661}, complete_flag = 1703 });
                list.Add(new SideEntry { name = "料理20　2/2", page = 15, quest_name = "料理20", quest_step = 2, quest_total = 2, event_id = 0u, map_id = 0u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{}, clear_flags = new List<int>{}, complete_flag = 0 });
                list.Add(new SideEntry { name = "料理大师", page = 15, quest_name = "料理大师", quest_step = 0, quest_total = 0, event_id = 0u, map_id = 531u, x = 224f, y = 0f, z = -120f, angle = 122f, set_flags = new List<int>{}, clear_flags = new List<int>{}, complete_flag = 0 });
                _entries[15] = list;
            }
            {
                var list = new List<SideEntry>();
                list.Add(new SideEntry { name = "地图変化5", page = 16, quest_name = "地图変化5", quest_step = 0, quest_total = 0, event_id = 4037999u, map_id = 380u, x = -50f, y = 150f, z = -366f, angle = 160f, set_flags = new List<int>{}, clear_flags = new List<int>{1570}, complete_flag = 0 });
                list.Add(new SideEntry { name = "最终城市探索1", page = 16, quest_name = "最终城市探索1", quest_step = 0, quest_total = 0, event_id = 4034000u, map_id = 234u, x = 19f, y = 10f, z = 283f, angle = 250f, set_flags = new List<int>{1519,1534,1563,1570,1569}, clear_flags = new List<int>{1571}, complete_flag = 1569 });
                list.Add(new SideEntry { name = "最终城市探索　卢克", page = 16, quest_name = "最终城市探索　卢克", quest_step = 0, quest_total = 0, event_id = 4035000u, map_id = 104u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{1571}, clear_flags = new List<int>{1572}, complete_flag = 0 });
                list.Add(new SideEntry { name = "最终城市探索　缇娅", page = 16, quest_name = "最终城市探索　缇娅", quest_step = 0, quest_total = 0, event_id = 4035000u, map_id = 614u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{1571}, clear_flags = new List<int>{1573}, complete_flag = 0 });
                list.Add(new SideEntry { name = "最终城市探索　杰德", page = 16, quest_name = "最终城市探索　杰德", quest_step = 0, quest_total = 0, event_id = 4035000u, map_id = 544u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{1571}, clear_flags = new List<int>{1574}, complete_flag = 0 });
                list.Add(new SideEntry { name = "最终城市探索　凯", page = 16, quest_name = "最终城市探索　凯", quest_step = 0, quest_total = 0, event_id = 4035000u, map_id = 375u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{1571}, clear_flags = new List<int>{1575}, complete_flag = 0 });
                list.Add(new SideEntry { name = "最终城市探索　阿尼丝", page = 16, quest_name = "最终城市探索　阿尼丝", quest_step = 0, quest_total = 0, event_id = 4035000u, map_id = 138u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{1571}, clear_flags = new List<int>{1576}, complete_flag = 0 });
                list.Add(new SideEntry { name = "最终城市探索　娜塔莉亚", page = 16, quest_name = "最终城市探索　娜塔莉亚", quest_step = 0, quest_total = 0, event_id = 4035000u, map_id = 69u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{1571}, clear_flags = new List<int>{1577}, complete_flag = 0 });
                list.Add(new SideEntry { name = "屠龙者开放", page = 16, quest_name = "屠龙者开放", quest_step = 0, quest_total = 0, event_id = 4037000u, map_id = 430u, x = 1009f, y = 71f, z = -1620f, angle = 180f, set_flags = new List<int>{1435,1437}, clear_flags = new List<int>{1612}, complete_flag = 0 });
                _entries[16] = list;
            }
            {
                var list = new List<SideEntry>();
                list.Add(new SideEntry { name = "屠龙者通关", page = 17, quest_name = "屠龙者通关", quest_step = 0, quest_total = 0, event_id = 4037000u, map_id = 430u, x = -442f, y = 71f, z = -699f, angle = 270f, set_flags = new List<int>{1435,1437,1476,1612}, clear_flags = new List<int>{1613}, complete_flag = 1612 });
                list.Add(new SideEntry { name = "屠龙者2周目", page = 17, quest_name = "屠龙者2周目", quest_step = 0, quest_total = 0, event_id = 4037000u, map_id = 430u, x = -442f, y = 71f, z = -699f, angle = 270f, set_flags = new List<int>{2013,1435,1437,1476,1612}, clear_flags = new List<int>{1613}, complete_flag = 1612 });
                list.Add(new SideEntry { name = "蚁狮人偶", page = 17, quest_name = "蚁狮人偶", quest_step = 0, quest_total = 0, event_id = 4039999u, map_id = 430u, x = 1009f, y = 71f, z = -1620f, angle = 180f, set_flags = new List<int>{1563}, clear_flags = new List<int>{1616,1477}, complete_flag = 0 });
                list.Add(new SideEntry { name = "skit播放", page = 17, quest_name = "skit播放", quest_step = 0, quest_total = 0, event_id = 0u, map_id = 541u, x = 15f, y = 0f, z = 156f, angle = 180f, set_flags = new List<int>{2013,1000,1563}, clear_flags = new List<int>{1617}, complete_flag = 0 });
                list.Add(new SideEntry { name = "movie播放", page = 17, quest_name = "movie播放", quest_step = 0, quest_total = 0, event_id = 4039999u, map_id = 432u, x = 585f, y = 0f, z = -527f, angle = 300f, set_flags = new List<int>{1583}, clear_flags = new List<int>{1618}, complete_flag = 1583 });
                list.Add(new SideEntry { name = "人物名鉴", page = 17, quest_name = "人物名鉴", quest_step = 0, quest_total = 0, event_id = 4039999u, map_id = 620u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{}, clear_flags = new List<int>{1753}, complete_flag = 0 });
                list.Add(new SideEntry { name = "斗技场1", page = 17, quest_name = "斗技场1", quest_step = 0, quest_total = 0, event_id = 3030000u, map_id = 75u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{}, clear_flags = new List<int>{1566}, complete_flag = 0 });
                list.Add(new SideEntry { name = "斗技场2", page = 17, quest_name = "斗技场2", quest_step = 0, quest_total = 0, event_id = 3030000u, map_id = 75u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{}, clear_flags = new List<int>{1478,1479,1480,1481}, complete_flag = 0 });
                list.Add(new SideEntry { name = "斗技场3", page = 17, quest_name = "斗技场3", quest_step = 0, quest_total = 0, event_id = 3030000u, map_id = 75u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{}, clear_flags = new List<int>{1478,1479,1480,1481}, complete_flag = 0 });
                _entries[17] = list;
            }
            {
                var list = new List<SideEntry>();
                list.Add(new SideEntry { name = "斗技场4", page = 18, quest_name = "斗技场4", quest_step = 0, quest_total = 0, event_id = 3030000u, map_id = 75u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{1478}, clear_flags = new List<int>{1479,1480,1481}, complete_flag = 1478 });
                list.Add(new SideEntry { name = "斗技场5", page = 18, quest_name = "斗技场5", quest_step = 0, quest_total = 0, event_id = 3030000u, map_id = 75u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{}, clear_flags = new List<int>{1478,1479,1480,1481}, complete_flag = 0 });
                list.Add(new SideEntry { name = "斗技场6", page = 18, quest_name = "斗技场6", quest_step = 0, quest_total = 0, event_id = 3030000u, map_id = 75u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{1480}, clear_flags = new List<int>{1478,1479,1481}, complete_flag = 1480 });
                list.Add(new SideEntry { name = "斗技场7", page = 18, quest_name = "斗技场7", quest_step = 0, quest_total = 0, event_id = 3030000u, map_id = 75u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{1478,1479,1480,1481}, clear_flags = new List<int>{}, complete_flag = 1481 });
                list.Add(new SideEntry { name = "SS道场", page = 18, quest_name = "SS道场", quest_step = 0, quest_total = 0, event_id = 3030000u, map_id = 80u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{2009,1481,1479}, clear_flags = new List<int>{1207}, complete_flag = 1479 });
                list.Add(new SideEntry { name = "道具收集者　1/2", page = 18, quest_name = "道具收集者", quest_step = 1, quest_total = 2, event_id = 4035150u, map_id = 149u, x = 349f, y = 0f, z = -2137f, angle = 180f, set_flags = new List<int>{}, clear_flags = new List<int>{1662,1663,1664,1493}, complete_flag = 0 });
                list.Add(new SideEntry { name = "道具收集者　2/2", page = 18, quest_name = "道具收集者", quest_step = 2, quest_total = 2, event_id = 4035150u, map_id = 139u, x = 165f, y = 0f, z = -100f, angle = 180f, set_flags = new List<int>{1662}, clear_flags = new List<int>{1663,1664,1493}, complete_flag = 1662 });
                list.Add(new SideEntry { name = "魔物收集者", page = 18, quest_name = "魔物收集者", quest_step = 0, quest_total = 0, event_id = 4034000u, map_id = 536u, x = 0f, y = 1f, z = 0f, angle = 0f, set_flags = new List<int>{}, clear_flags = new List<int>{1665,1494}, complete_flag = 0 });
                list.Add(new SideEntry { name = "合成屋开放", page = 18, quest_name = "合成屋开放", quest_step = 0, quest_total = 0, event_id = 0u, map_id = 243u, x = 54f, y = 1f, z = -47f, angle = 180f, set_flags = new List<int>{}, clear_flags = new List<int>{1495}, complete_flag = 0 });
                _entries[18] = list;
            }
            {
                var list = new List<SideEntry>();
                list.Add(new SideEntry { name = "凯称号5", page = 19, quest_name = "凯称号5", quest_step = 0, quest_total = 0, event_id = 4036000u, map_id = 80u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{2009,1207,1200,1201,1202,1203,1204,1205,1206}, clear_flags = new List<int>{}, complete_flag = 1206 });
                list.Add(new SideEntry { name = "缇娅称号8", page = 19, quest_name = "缇娅称号8", quest_step = 0, quest_total = 0, event_id = 4036000u, map_id = 104u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{}, clear_flags = new List<int>{}, complete_flag = 0 });
                list.Add(new SideEntry { name = "杰德称号9", page = 19, quest_name = "杰德称号9", quest_step = 0, quest_total = 0, event_id = 4034000u, map_id = 243u, x = 54f, y = 1f, z = -47f, angle = 180f, set_flags = new List<int>{521}, clear_flags = new List<int>{1208}, complete_flag = 521 });
                list.Add(new SideEntry { name = "阿尼丝称号14　1/2", page = 19, quest_name = "阿尼丝称号14", quest_step = 1, quest_total = 2, event_id = 4039999u, map_id = 608u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{}, clear_flags = new List<int>{1733}, complete_flag = 0 });
                list.Add(new SideEntry { name = "阿尼丝称号14　2/2", page = 19, quest_name = "阿尼丝称号14", quest_step = 2, quest_total = 2, event_id = 4039999u, map_id = 583u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{}, clear_flags = new List<int>{1733}, complete_flag = 0 });
                list.Add(new SideEntry { name = "凯称号12　1/2", page = 19, quest_name = "凯称号12", quest_step = 1, quest_total = 2, event_id = 4039060u, map_id = 374u, x = 480f, y = 5f, z = 6f, angle = 90f, set_flags = new List<int>{118}, clear_flags = new List<int>{1737}, complete_flag = 118 });
                list.Add(new SideEntry { name = "凯称号12　2/2", page = 19, quest_name = "凯称号12", quest_step = 2, quest_total = 2, event_id = 0u, map_id = 0u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{}, clear_flags = new List<int>{}, complete_flag = 0 });
                list.Add(new SideEntry { name = "卢克称号19　狂战士", page = 19, quest_name = "卢克称号19　狂战士", quest_step = 0, quest_total = 0, event_id = 4039999u, map_id = 79u, x = 2360f, y = 1876f, z = 2356f, angle = 270f, set_flags = new List<int>{}, clear_flags = new List<int>{}, complete_flag = 0 });
                list.Add(new SideEntry { name = "卢克称号20", page = 19, quest_name = "卢克称号20", quest_step = 0, quest_total = 0, event_id = 0u, map_id = 102u, x = 1044f, y = 0f, z = -83f, angle = 320f, set_flags = new List<int>{1643,1414,1523}, clear_flags = new List<int>{1340}, complete_flag = 1523 });
                _entries[19] = list;
            }
            {
                var list = new List<SideEntry>();
                list.Add(new SideEntry { name = "娜塔莉亚称号5", page = 20, quest_name = "娜塔莉亚称号5", quest_step = 0, quest_total = 0, event_id = 0u, map_id = 243u, x = 54f, y = 1f, z = -47f, angle = 180f, set_flags = new List<int>{1495,1879,1880,1881,1882,1883,1884}, clear_flags = new List<int>{}, complete_flag = 1884 });
                list.Add(new SideEntry { name = "娜塔莉亚称号14", page = 20, quest_name = "娜塔莉亚称号14", quest_step = 0, quest_total = 0, event_id = 0u, map_id = 243u, x = 54f, y = 1f, z = -47f, angle = 180f, set_flags = new List<int>{1495,1879,1880,1881,1882,1883,1884,1885,1886,1887,1888,1889,1890,1891,1892,1893,1894,1895,1896,1897,1898,1899,1900,1901,1902,1903,1904,1905,1906}, clear_flags = new List<int>{}, complete_flag = 1906 });
                list.Add(new SideEntry { name = "阿卢比奥尔能力提升2", page = 20, quest_name = "阿卢比奥尔能力提升2", quest_step = 0, quest_total = 0, event_id = 4039999u, map_id = 380u, x = -19f, y = 153f, z = -502f, angle = 123f, set_flags = new List<int>{1210}, clear_flags = new List<int>{1734}, complete_flag = 1210 });
                list.Add(new SideEntry { name = "阿卢比奥尔能力提升3", page = 20, quest_name = "阿卢比奥尔能力提升3", quest_step = 0, quest_total = 0, event_id = 4039999u, map_id = 380u, x = -19f, y = 153f, z = -502f, angle = 123f, set_flags = new List<int>{}, clear_flags = new List<int>{1735,1734}, complete_flag = 0 });
                list.Add(new SideEntry { name = "跟塔尔罗玩追逐游戏", page = 20, quest_name = "跟塔尔罗玩追逐游戏", quest_step = 0, quest_total = 0, event_id = 0u, map_id = 0u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{}, clear_flags = new List<int>{}, complete_flag = 0 });
                list.Add(new SideEntry { name = "扎雷霍火山2回目", page = 20, quest_name = "扎雷霍火山2回目", quest_step = 0, quest_total = 0, event_id = 4039999u, map_id = 515u, x = -335f, y = 1f, z = -1348f, angle = 300f, set_flags = new List<int>{1620}, clear_flags = new List<int>{1209,1210}, complete_flag = 1620 });
                list.Add(new SideEntry { name = "绘画", page = 20, quest_name = "绘画", quest_step = 0, quest_total = 0, event_id = 3025090u, map_id = 571u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{1332}, clear_flags = new List<int>{1620,1621}, complete_flag = 1332 });
                list.Add(new SideEntry { name = "缇娅的吊坠1/2", page = 20, quest_name = "缇娅的吊坠", quest_step = 1, quest_total = 2, event_id = 3025100u, map_id = 215u, x = -926f, y = 0f, z = 2350f, angle = 0f, set_flags = new List<int>{1021}, clear_flags = new List<int>{1584}, complete_flag = 0 });
                list.Add(new SideEntry { name = "缇娅的吊坠2/2", page = 20, quest_name = "缇娅的吊坠", quest_step = 2, quest_total = 2, event_id = 3025100u, map_id = 588u, x = 27f, y = 4f, z = 728f, angle = 180f, set_flags = new List<int>{1021,1584}, clear_flags = new List<int>{1585,1586,1587}, complete_flag = 1584 });
                _entries[20] = list;
            }
            {
                var list = new List<SideEntry>();
                list.Add(new SideEntry { name = "噩梦缠身的卢克", page = 21, quest_name = "噩梦缠身的卢克", quest_step = 0, quest_total = 0, event_id = 0u, map_id = 0u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{}, clear_flags = new List<int>{}, complete_flag = 0 });
                list.Add(new SideEntry { name = "饥饿的人们1/3", page = 21, quest_name = "饥饿的人们", quest_step = 1, quest_total = 3, event_id = 3026000u, map_id = 292u, x = 70f, y = 4f, z = -1891f, angle = 0f, set_flags = new List<int>{}, clear_flags = new List<int>{1772}, complete_flag = 0 });
                list.Add(new SideEntry { name = "饥饿的人们2/3", page = 21, quest_name = "饥饿的人们", quest_step = 2, quest_total = 3, event_id = 3026000u, map_id = 597u, x = 34f, y = 0f, z = -553f, angle = 180f, set_flags = new List<int>{1595}, clear_flags = new List<int>{1597}, complete_flag = 1595 });
                list.Add(new SideEntry { name = "饥饿的人们3/3", page = 21, quest_name = "饥饿的人们", quest_step = 3, quest_total = 3, event_id = 3030050u, map_id = 87u, x = 36f, y = 0f, z = -765f, angle = 180f, set_flags = new List<int>{1596}, clear_flags = new List<int>{1597,1598}, complete_flag = 1596 });
                list.Add(new SideEntry { name = "福林格斯和塞西尔1/10", page = 21, quest_name = "福林格斯和塞西尔", quest_step = 1, quest_total = 10, event_id = 3025000u, map_id = 59u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{1598}, clear_flags = new List<int>{1666,1667,1668}, complete_flag = 1598 });
                list.Add(new SideEntry { name = "福林格斯和塞西尔2/10", page = 21, quest_name = "福林格斯和塞西尔", quest_step = 2, quest_total = 10, event_id = 3025000u, map_id = 61u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{1778}, clear_flags = new List<int>{1666}, complete_flag = 1778 });
                list.Add(new SideEntry { name = "福林格斯和塞西尔3/10", page = 21, quest_name = "福林格斯和塞西尔", quest_step = 3, quest_total = 10, event_id = 3025000u, map_id = 63u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{1598,1666}, clear_flags = new List<int>{1667}, complete_flag = 1666 });
                list.Add(new SideEntry { name = "福林格斯和塞西尔4/10", page = 21, quest_name = "福林格斯和塞西尔", quest_step = 4, quest_total = 10, event_id = 3030140u, map_id = 292u, x = 239f, y = 4f, z = -2660f, angle = 0f, set_flags = new List<int>{1783}, clear_flags = new List<int>{1671}, complete_flag = 1783 });
                list.Add(new SideEntry { name = "福林格斯和塞西尔5/10", page = 21, quest_name = "福林格斯和塞西尔", quest_step = 5, quest_total = 10, event_id = 3025000u, map_id = 292u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{1670}, clear_flags = new List<int>{1783}, complete_flag = 1670 });
                _entries[21] = list;
            }
            {
                var list = new List<SideEntry>();
                list.Add(new SideEntry { name = "福林格斯和塞西尔6/10", page = 22, quest_name = "福林格斯和塞西尔", quest_step = 6, quest_total = 10, event_id = 3025000u, map_id = 299u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{1598,1671}, clear_flags = new List<int>{1672,1673,1674,1676,1677}, complete_flag = 1671 });
                list.Add(new SideEntry { name = "福林格斯和塞西尔7/10", page = 22, quest_name = "福林格斯和塞西尔", quest_step = 7, quest_total = 10, event_id = 3025000u, map_id = 250u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{1674}, clear_flags = new List<int>{1784}, complete_flag = 1674 });
                list.Add(new SideEntry { name = "福林格斯和塞西尔8/10", page = 22, quest_name = "福林格斯和塞西尔", quest_step = 8, quest_total = 10, event_id = 4034210u, map_id = 70u, x = -140f, y = 3f, z = 461f, angle = 0f, set_flags = new List<int>{1678}, clear_flags = new List<int>{1679}, complete_flag = 1678 });
                list.Add(new SideEntry { name = "福林格斯和塞西尔9/10", page = 22, quest_name = "福林格斯和塞西尔", quest_step = 9, quest_total = 10, event_id = 4038030u, map_id = 322u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{1680}, clear_flags = new List<int>{1681}, complete_flag = 1680 });
                list.Add(new SideEntry { name = "福林格斯和塞西尔10/10", page = 22, quest_name = "福林格斯和塞西尔", quest_step = 10, quest_total = 10, event_id = 4038030u, map_id = 69u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{1681}, clear_flags = new List<int>{1682}, complete_flag = 1681 });
                list.Add(new SideEntry { name = "寻找兔猪1/2", page = 22, quest_name = "寻找兔猪", quest_step = 1, quest_total = 2, event_id = 4034000u, map_id = 595u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{}, clear_flags = new List<int>{1684}, complete_flag = 0 });
                list.Add(new SideEntry { name = "寻找兔猪2/2", page = 22, quest_name = "寻找兔猪", quest_step = 2, quest_total = 2, event_id = 4034000u, map_id = 596u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{1684,1691}, clear_flags = new List<int>{1692}, complete_flag = 1691 });
                list.Add(new SideEntry { name = "医生杰德", page = 22, quest_name = "医生杰德", quest_step = 0, quest_total = 0, event_id = 4038030u, map_id = 453u, x = -787f, y = 9f, z = 137f, angle = 270f, set_flags = new List<int>{}, clear_flags = new List<int>{1695,1696}, complete_flag = 0 });
                list.Add(new SideEntry { name = "决战装束", page = 22, quest_name = "决战装束", quest_step = 0, quest_total = 0, event_id = 4039060u, map_id = 597u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{1598}, clear_flags = new List<int>{1697}, complete_flag = 1598 });
                _entries[22] = list;
            }
            {
                var list = new List<SideEntry>();
                list.Add(new SideEntry { name = "缇娅女仆", page = 23, quest_name = "缇娅女仆", quest_step = 0, quest_total = 0, event_id = 3030040u, map_id = 92u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{}, clear_flags = new List<int>{1698,1699,1700,1701}, complete_flag = 0 });
                list.Add(new SideEntry { name = "卢克正装", page = 23, quest_name = "卢克正装", quest_step = 0, quest_total = 0, event_id = 4038100u, map_id = 98u, x = -347f, y = 50f, z = -10f, angle = 180f, set_flags = new List<int>{}, clear_flags = new List<int>{1702,1703,1704,1705}, complete_flag = 0 });
                list.Add(new SideEntry { name = "蘑菇之路", page = 23, quest_name = "蘑菇之路", quest_step = 0, quest_total = 0, event_id = 3030120u, map_id = 98u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{}, clear_flags = new List<int>{1211,1212,1213,1214,1215,1216,1217,1218,1219,1220,1221,1222,1223}, complete_flag = 0 });
                list.Add(new SideEntry { name = "石碑巡礼之旅", page = 23, quest_name = "石碑巡礼之旅", quest_step = 0, quest_total = 0, event_id = 4039999u, map_id = 140u, x = 815f, y = 580f, z = -2094f, angle = 90f, set_flags = new List<int>{}, clear_flags = new List<int>{1706,1712,1707,1713,1708,1714,1498}, complete_flag = 0 });
                list.Add(new SideEntry { name = "杰德人格特质1　1/3", page = 23, quest_name = "杰德人格特质1", quest_step = 1, quest_total = 3, event_id = 4039999u, map_id = 580u, x = -761f, y = 11f, z = 132f, angle = 270f, set_flags = new List<int>{}, clear_flags = new List<int>{1727,1728,1729}, complete_flag = 0 });
                list.Add(new SideEntry { name = "杰德人格特质1　2/3", page = 23, quest_name = "杰德人格特质1", quest_step = 2, quest_total = 3, event_id = 0u, map_id = 383u, x = 0f, y = 1f, z = 0f, angle = 0f, set_flags = new List<int>{1727}, clear_flags = new List<int>{1728,1729}, complete_flag = 1727 });
                list.Add(new SideEntry { name = "杰德人格特质1　3/3", page = 23, quest_name = "杰德人格特质1", quest_step = 3, quest_total = 3, event_id = 4036090u, map_id = 580u, x = -2008f, y = 10f, z = 313f, angle = 280f, set_flags = new List<int>{1727,1728}, clear_flags = new List<int>{1729}, complete_flag = 1728 });
                list.Add(new SideEntry { name = "杰德人格特质2", page = 23, quest_name = "杰德人格特质2", quest_step = 0, quest_total = 0, event_id = 4034000u, map_id = 596u, x = 0f, y = 1f, z = 0f, angle = 0f, set_flags = new List<int>{1638,1625}, clear_flags = new List<int>{1730,1731,1732}, complete_flag = 1638 });
                list.Add(new SideEntry { name = "死灵使杰德1/6", page = 23, quest_name = "死灵使杰德", quest_step = 1, quest_total = 6, event_id = 4034000u, map_id = 581u, x = 0f, y = 1f, z = 0f, angle = 0f, set_flags = new List<int>{}, clear_flags = new List<int>{1718,1719,1720,1721,1722}, complete_flag = 0 });
                _entries[23] = list;
            }
            {
                var list = new List<SideEntry>();
                list.Add(new SideEntry { name = "死灵使杰德2/6", page = 24, quest_name = "死灵使杰德", quest_step = 2, quest_total = 6, event_id = 4034000u, map_id = 583u, x = 0f, y = 1f, z = 0f, angle = 0f, set_flags = new List<int>{1718}, clear_flags = new List<int>{1719,1720,1721,1722}, complete_flag = 1718 });
                list.Add(new SideEntry { name = "死灵使杰德3/6", page = 24, quest_name = "死灵使杰德", quest_step = 3, quest_total = 6, event_id = 4034000u, map_id = 579u, x = 507f, y = 11f, z = -2486f, angle = 100f, set_flags = new List<int>{1718,1719}, clear_flags = new List<int>{1720,1721,1722,1723}, complete_flag = 1719 });
                list.Add(new SideEntry { name = "死灵使杰德4/6", page = 24, quest_name = "死灵使杰德", quest_step = 4, quest_total = 6, event_id = 4034000u, map_id = 597u, x = 0f, y = 1f, z = 0f, angle = 0f, set_flags = new List<int>{1718,1719,1720}, clear_flags = new List<int>{1721,1722,1723}, complete_flag = 1720 });
                list.Add(new SideEntry { name = "死灵使杰德5/6", page = 24, quest_name = "死灵使杰德", quest_step = 5, quest_total = 6, event_id = 4034000u, map_id = 594u, x = 0f, y = 1f, z = 0f, angle = 0f, set_flags = new List<int>{1718,1719,1720,1721}, clear_flags = new List<int>{1722,1723}, complete_flag = 1721 });
                list.Add(new SideEntry { name = "死灵使杰德6/6", page = 24, quest_name = "死灵使杰德", quest_step = 6, quest_total = 6, event_id = 4034000u, map_id = 581u, x = 0f, y = 1f, z = 0f, angle = 0f, set_flags = new List<int>{1718,1719,1720,1721,1722}, clear_flags = new List<int>{1723}, complete_flag = 1722 });
                list.Add(new SideEntry { name = "王牌·赫本利事件1/5", page = 24, quest_name = "王牌·赫本利事件", quest_step = 1, quest_total = 5, event_id = 0u, map_id = 599u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{}, clear_flags = new List<int>{1740,1741,1742,1743,1744}, complete_flag = 0 });
                list.Add(new SideEntry { name = "王牌·赫本利事件2/5", page = 24, quest_name = "王牌·赫本利事件", quest_step = 2, quest_total = 5, event_id = 0u, map_id = 59u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{1740}, clear_flags = new List<int>{1741,1742,1743,1744}, complete_flag = 1740 });
                list.Add(new SideEntry { name = "王牌·赫本利事件3/5", page = 24, quest_name = "王牌·赫本利事件", quest_step = 3, quest_total = 5, event_id = 0u, map_id = 61u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{1740,1741}, clear_flags = new List<int>{1742,1743,1744}, complete_flag = 1741 });
                list.Add(new SideEntry { name = "王牌·赫本利事件4/5", page = 24, quest_name = "王牌·赫本利事件", quest_step = 4, quest_total = 5, event_id = 0u, map_id = 582u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{1740,1741,1742}, clear_flags = new List<int>{1743,1744}, complete_flag = 1742 });
                _entries[24] = list;
            }
            {
                var list = new List<SideEntry>();
                list.Add(new SideEntry { name = "王牌·赫本利事件5/5", page = 25, quest_name = "王牌·赫本利事件", quest_step = 5, quest_total = 5, event_id = 0u, map_id = 597u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{1740,1741,1742,1743}, clear_flags = new List<int>{1744}, complete_flag = 1743 });
                list.Add(new SideEntry { name = "音元分合1/5", page = 25, quest_name = "音元分合", quest_step = 1, quest_total = 5, event_id = 1008040u, map_id = 70u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{}, clear_flags = new List<int>{1745}, complete_flag = 0 });
                list.Add(new SideEntry { name = "音元分合2/5", page = 25, quest_name = "音元分合", quest_step = 2, quest_total = 5, event_id = 3032000u, map_id = 374u, x = 36f, y = 4f, z = 253f, angle = 0f, set_flags = new List<int>{}, clear_flags = new List<int>{1746}, complete_flag = 0 });
                list.Add(new SideEntry { name = "音元分合3/5", page = 25, quest_name = "音元分合", quest_step = 3, quest_total = 5, event_id = 4034010u, map_id = 380u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{1746}, clear_flags = new List<int>{1747}, complete_flag = 1746 });
                list.Add(new SideEntry { name = "音元分合4/5", page = 25, quest_name = "音元分合", quest_step = 4, quest_total = 5, event_id = 4038999u, map_id = 450u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{1747}, clear_flags = new List<int>{1748,1749}, complete_flag = 1747 });
                list.Add(new SideEntry { name = "音元分合5/5", page = 25, quest_name = "音元分合", quest_step = 5, quest_total = 5, event_id = 4039180u, map_id = 583u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{1749,1643}, clear_flags = new List<int>{1750}, complete_flag = 1643 });
                list.Add(new SideEntry { name = "杰德必杀技·导入（塞斯曼对话）", page = 25, quest_name = "杰德必杀技·导入（塞斯曼对话）", quest_step = 0, quest_total = 0, event_id = 2020000u, map_id = 608u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{}, clear_flags = new List<int>{1474}, complete_flag = 0 });
                list.Add(new SideEntry { name = "杰德必杀技·导入２（老马克嘉万对话）", page = 25, quest_name = "杰德必杀技·导入２（老马克嘉万对话）", quest_step = 0, quest_total = 0, event_id = 0u, map_id = 485u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{}, clear_flags = new List<int>{1754}, complete_flag = 0 });
                list.Add(new SideEntry { name = "杰德必杀技·石发现（克塞多尼亚）", page = 25, quest_name = "杰德必杀技·石发现（克塞多尼亚）", quest_step = 0, quest_total = 0, event_id = 0u, map_id = 240u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{1754}, clear_flags = new List<int>{1755,1756}, complete_flag = 0 });
                _entries[25] = list;
            }
            {
                var list = new List<SideEntry>();
                list.Add(new SideEntry { name = "杰德必杀技·石发现（克特尔堡）", page = 26, quest_name = "杰德必杀技·石发现（克特尔堡）", quest_step = 0, quest_total = 0, event_id = 0u, map_id = 513u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{1754}, clear_flags = new List<int>{1757,1758}, complete_flag = 0 });
                list.Add(new SideEntry { name = "杰德必杀技·石发现（杰利达）", page = 26, quest_name = "杰德必杀技·石发现（杰利达）", quest_step = 0, quest_total = 0, event_id = 0u, map_id = 376u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{1754}, clear_flags = new List<int>{1759}, complete_flag = 0 });
                list.Add(new SideEntry { name = "杰德必杀技·石三个绝对零度取得", page = 26, quest_name = "杰德必杀技·石三个绝对零度取得", quest_step = 0, quest_total = 0, event_id = 0u, map_id = 240u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{1754,1758,1759,1767,1768,1756}, clear_flags = new List<int>{1756,1766,1769,1757,1759}, complete_flag = 1756 });
                list.Add(new SideEntry { name = "杰德必杀技·石发现（释放之门）", page = 26, quest_name = "杰德必杀技·石发现（释放之门）", quest_step = 0, quest_total = 0, event_id = 4035000u, map_id = 436u, x = -1400f, y = -140f, z = -2070f, angle = 0f, set_flags = new List<int>{1754}, clear_flags = new List<int>{1760}, complete_flag = 0 });
                list.Add(new SideEntry { name = "杰德必杀技·石发现（贝尔肯德）", page = 26, quest_name = "杰德必杀技·石发现（贝尔肯德）", quest_step = 0, quest_total = 0, event_id = 0u, map_id = 455u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{1754}, clear_flags = new List<int>{1761}, complete_flag = 0 });
                list.Add(new SideEntry { name = "杰德必杀技·石发现（凯兹尔港）", page = 26, quest_name = "杰德必杀技·石发现（凯兹尔港）", quest_step = 0, quest_total = 0, event_id = 0u, map_id = 297u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{1754}, clear_flags = new List<int>{1762}, complete_flag = 0 });
                list.Add(new SideEntry { name = "杰德必杀技·石三个虹光之刃取得", page = 26, quest_name = "杰德必杀技·石三个虹光之刃取得", quest_step = 0, quest_total = 0, event_id = 0u, map_id = 436u, x = -1400f, y = -140f, z = -2070f, angle = 0f, set_flags = new List<int>{1754,1761,1762,1766,1768,1760}, clear_flags = new List<int>{1760,1767,1769,1761,1762}, complete_flag = 1760 });
                list.Add(new SideEntry { name = "杰德必杀技·最后的石收集", page = 26, quest_name = "杰德必杀技·最后的石收集", quest_step = 0, quest_total = 0, event_id = 4039060u, map_id = 147u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{1754,1659,1764,1765,1763}, clear_flags = new List<int>{1763,1764,1765}, complete_flag = 1763 });
                list.Add(new SideEntry { name = "地图变化3　1/5", page = 26, quest_name = "地图变化3", quest_step = 1, quest_total = 5, event_id = 4037000u, map_id = 60u, x = -300f, y = -3f, z = -450f, angle = 0f, set_flags = new List<int>{}, clear_flags = new List<int>{1298,1568,1569}, complete_flag = 0 });
                _entries[26] = list;
            }
            {
                var list = new List<SideEntry>();
                list.Add(new SideEntry { name = "地图变化3　2/5", page = 27, quest_name = "地图变化3", quest_step = 2, quest_total = 5, event_id = 4037000u, map_id = 62u, x = 123f, y = -2f, z = 64f, angle = 222f, set_flags = new List<int>{1298}, clear_flags = new List<int>{1568,1569}, complete_flag = 1298 });
                list.Add(new SideEntry { name = "地图变化3　3/5", page = 27, quest_name = "地图变化3", quest_step = 3, quest_total = 5, event_id = 4037000u, map_id = 62u, x = 123f, y = -2f, z = 64f, angle = 222f, set_flags = new List<int>{1298,1897,1888}, clear_flags = new List<int>{1568}, complete_flag = 1888 });
                list.Add(new SideEntry { name = "地图变化3　4/5", page = 27, quest_name = "地图变化3", quest_step = 4, quest_total = 5, event_id = 4037000u, map_id = 60u, x = -300f, y = -3f, z = -450f, angle = 0f, set_flags = new List<int>{1298,1568}, clear_flags = new List<int>{1569}, complete_flag = 1568 });
                list.Add(new SideEntry { name = "地图变化3　5/5", page = 27, quest_name = "地图变化3", quest_step = 5, quest_total = 5, event_id = 0u, map_id = 0u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{}, clear_flags = new List<int>{}, complete_flag = 0 });
                list.Add(new SideEntry { name = "八音盒EX　1/2", page = 27, quest_name = "八音盒EX", quest_step = 1, quest_total = 2, event_id = 0u, map_id = 367u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{2013,1554}, clear_flags = new List<int>{1486,1487}, complete_flag = 1554 });
                list.Add(new SideEntry { name = "八音盒EX　2/2", page = 27, quest_name = "八音盒EX", quest_step = 2, quest_total = 2, event_id = 0u, map_id = 391u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{2013,1554,1486}, clear_flags = new List<int>{1487}, complete_flag = 1486 });
                list.Add(new SideEntry { name = "EX迷宫　1/2", page = 27, quest_name = "EX迷宫", quest_step = 1, quest_total = 2, event_id = 4039190u, map_id = 376u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{409,410,1451,1453,1454}, clear_flags = new List<int>{1451,1453,1454,1455}, complete_flag = 1454 });
                list.Add(new SideEntry { name = "EX迷宫　2/2", page = 27, quest_name = "EX迷宫", quest_step = 2, quest_total = 2, event_id = 4039190u, map_id = 254u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{1455,1456,3300,1457,1458,1459}, clear_flags = new List<int>{1456,1457,1458,1313,1461,1459,1314,1460}, complete_flag = 1459 });
                list.Add(new SideEntry { name = "梵和凯1/3", page = 27, quest_name = "梵和凯", quest_step = 1, quest_total = 3, event_id = 0u, map_id = 509u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{}, clear_flags = new List<int>{1786,1482}, complete_flag = 0 });
                _entries[27] = list;
            }
            {
                var list = new List<SideEntry>();
                list.Add(new SideEntry { name = "梵和凯2/3", page = 28, quest_name = "梵和凯", quest_step = 2, quest_total = 3, event_id = 3027100u, map_id = 443u, x = -2800f, y = -14f, z = 360f, angle = 0f, set_flags = new List<int>{1482}, clear_flags = new List<int>{1483}, complete_flag = 1482 });
                list.Add(new SideEntry { name = "梵和凯3/3", page = 28, quest_name = "梵和凯", quest_step = 3, quest_total = 3, event_id = 3027100u, map_id = 445u, x = -209f, y = 0f, z = -278f, angle = 303f, set_flags = new List<int>{1483}, clear_flags = new List<int>{1787,1484,1788,1485}, complete_flag = 1483 });
                list.Add(new SideEntry { name = "卢克奥义书1/6", page = 28, quest_name = "卢克奥义书", quest_step = 1, quest_total = 6, event_id = 1008070u, map_id = 98u, x = -300f, y = 0f, z = 350f, angle = 0f, set_flags = new List<int>{}, clear_flags = new List<int>{1789,1790}, complete_flag = 0 });
                list.Add(new SideEntry { name = "卢克奥义书2/6", page = 28, quest_name = "卢克奥义书", quest_step = 2, quest_total = 6, event_id = 1008070u, map_id = 70u, x = -80f, y = 3f, z = -1670f, angle = 0f, set_flags = new List<int>{1789}, clear_flags = new List<int>{1790,1310}, complete_flag = 1789 });
                list.Add(new SideEntry { name = "卢克奥义书3/6", page = 28, quest_name = "卢克奥义书", quest_step = 3, quest_total = 6, event_id = 2023000u, map_id = 612u, x = 630f, y = 2f, z = -1200f, angle = 0f, set_flags = new List<int>{1790,1791,1792}, clear_flags = new List<int>{1791,1792}, complete_flag = 1792 });
                list.Add(new SideEntry { name = "卢克奥义书4/6", page = 28, quest_name = "卢克奥义书", quest_step = 4, quest_total = 6, event_id = 3032000u, map_id = 529u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{1793,1794,1796}, clear_flags = new List<int>{1794,1796,1797}, complete_flag = 1796 });
                list.Add(new SideEntry { name = "卢克奥义书5/6", page = 28, quest_name = "卢克奥义书", quest_step = 5, quest_total = 6, event_id = 4039060u, map_id = 150u, x = -150f, y = 0f, z = -3150f, angle = 0f, set_flags = new List<int>{1797,1798,1799}, clear_flags = new List<int>{1798,1799,1401}, complete_flag = 1799 });
                list.Add(new SideEntry { name = "卢克奥义书6/6", page = 28, quest_name = "卢克奥义书", quest_step = 6, quest_total = 6, event_id = 0u, map_id = 0u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{}, clear_flags = new List<int>{}, complete_flag = 0 });
                list.Add(new SideEntry { name = "拉尔戈的往事1/3", page = 28, quest_name = "拉尔戈的往事", quest_step = 1, quest_total = 3, event_id = 4038110u, map_id = 94u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{}, clear_flags = new List<int>{1402}, complete_flag = 0 });
                _entries[28] = list;
            }
            {
                var list = new List<SideEntry>();
                list.Add(new SideEntry { name = "拉尔戈的往事2/3", page = 29, quest_name = "拉尔戈的往事", quest_step = 2, quest_total = 3, event_id = 4038110u, map_id = 232u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{1402}, clear_flags = new List<int>{1403}, complete_flag = 1402 });
                list.Add(new SideEntry { name = "拉尔戈的往事3/3", page = 29, quest_name = "拉尔戈的往事", quest_step = 3, quest_total = 3, event_id = 4038170u, map_id = 551u, x = -65f, y = 9f, z = 1772f, angle = 0f, set_flags = new List<int>{1403}, clear_flags = new List<int>{1404}, complete_flag = 1403 });
                list.Add(new SideEntry { name = "阿尼丝的背叛1/4", page = 29, quest_name = "阿尼丝的背叛", quest_step = 1, quest_total = 4, event_id = 3029999u, map_id = 529u, x = 219f, y = 0f, z = -138f, angle = 0f, set_flags = new List<int>{}, clear_flags = new List<int>{1405}, complete_flag = 0 });
                list.Add(new SideEntry { name = "阿尼丝的背叛2/4", page = 29, quest_name = "阿尼丝的背叛", quest_step = 2, quest_total = 4, event_id = 3033999u, map_id = 139u, x = 544f, y = 0f, z = -656f, angle = 320f, set_flags = new List<int>{1406}, clear_flags = new List<int>{1407}, complete_flag = 1406 });
                list.Add(new SideEntry { name = "阿尼丝的背叛3/4", page = 29, quest_name = "阿尼丝的背叛", quest_step = 3, quest_total = 4, event_id = 4037260u, map_id = 374u, x = 1100f, y = 430f, z = -1950f, angle = 320f, set_flags = new List<int>{1408}, clear_flags = new List<int>{1409}, complete_flag = 1408 });
                list.Add(new SideEntry { name = "阿尼丝的背叛4/4", page = 29, quest_name = "阿尼丝的背叛", quest_step = 4, quest_total = 4, event_id = 0u, map_id = 0u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{}, clear_flags = new List<int>{}, complete_flag = 0 });
                list.Add(new SideEntry { name = "玛尔库特之星1/6", page = 29, quest_name = "玛尔库特之星", quest_step = 1, quest_total = 6, event_id = 4035000u, map_id = 430u, x = 1147f, y = 71f, z = -1600f, angle = 0f, set_flags = new List<int>{}, clear_flags = new List<int>{1430,1431,1432,1433,1434,1435,1436}, complete_flag = 0 });
                list.Add(new SideEntry { name = "玛尔库特之星2/6", page = 29, quest_name = "玛尔库特之星", quest_step = 2, quest_total = 6, event_id = 4035000u, map_id = 616u, x = 0f, y = 0f, z = 1000f, angle = 0f, set_flags = new List<int>{1430}, clear_flags = new List<int>{1431,1432,1433,1434,1435,1436}, complete_flag = 1430 });
                list.Add(new SideEntry { name = "玛尔库特之星3/6", page = 29, quest_name = "玛尔库特之星", quest_step = 3, quest_total = 6, event_id = 4035000u, map_id = 70u, x = -170f, y = 3f, z = 650f, angle = 0f, set_flags = new List<int>{1431}, clear_flags = new List<int>{1432,1433,1434,1435,1436}, complete_flag = 1431 });
                _entries[29] = list;
            }
            {
                var list = new List<SideEntry>();
                list.Add(new SideEntry { name = "玛尔库特之星4/6", page = 30, quest_name = "玛尔库特之星", quest_step = 4, quest_total = 6, event_id = 4035000u, map_id = 59u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{1432}, clear_flags = new List<int>{1433,1434,1435,1436,1437}, complete_flag = 1432 });
                list.Add(new SideEntry { name = "玛尔库特之星5/6", page = 30, quest_name = "玛尔库特之星", quest_step = 5, quest_total = 6, event_id = 4035000u, map_id = 422u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{1432,1433}, clear_flags = new List<int>{1434,1435,1436,1437}, complete_flag = 1433 });
                list.Add(new SideEntry { name = "玛尔库特之星6/6", page = 30, quest_name = "玛尔库特之星", quest_step = 6, quest_total = 6, event_id = 4035000u, map_id = 70u, x = -170f, y = 3f, z = 650f, angle = 0f, set_flags = new List<int>{1431,1435}, clear_flags = new List<int>{1436,1437}, complete_flag = 1431 });
                list.Add(new SideEntry { name = "凯的奥义书1/11", page = 30, quest_name = "凯的奥义书", quest_step = 1, quest_total = 11, event_id = 1009010u, map_id = 73u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{1010,1011}, clear_flags = new List<int>{1414}, complete_flag = 1011 });
                list.Add(new SideEntry { name = "凯的奥义书2/11", page = 30, quest_name = "凯的奥义书", quest_step = 2, quest_total = 11, event_id = 2013000u, map_id = 440u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{1414}, clear_flags = new List<int>{1415}, complete_flag = 0 });
                list.Add(new SideEntry { name = "凯的奥义书3/11", page = 30, quest_name = "凯的奥义书", quest_step = 3, quest_total = 11, event_id = 2013000u, map_id = 292u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{1415}, clear_flags = new List<int>{1416}, complete_flag = 1415 });
                list.Add(new SideEntry { name = "凯的奥义书4/11", page = 30, quest_name = "凯的奥义书", quest_step = 4, quest_total = 11, event_id = 2014000u, map_id = 140u, x = -860f, y = 500f, z = -3000f, angle = 0f, set_flags = new List<int>{1416}, clear_flags = new List<int>{1417}, complete_flag = 1416 });
                list.Add(new SideEntry { name = "凯的奥义书5/11", page = 30, quest_name = "凯的奥义书", quest_step = 5, quest_total = 11, event_id = 2019999u, map_id = 592u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{1417}, clear_flags = new List<int>{1418}, complete_flag = 1417 });
                list.Add(new SideEntry { name = "凯的奥义书6/11", page = 30, quest_name = "凯的奥义书", quest_step = 6, quest_total = 11, event_id = 0u, map_id = 443u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{1418}, clear_flags = new List<int>{1419}, complete_flag = 1418 });
                _entries[30] = list;
            }
            {
                var list = new List<SideEntry>();
                list.Add(new SideEntry { name = "凯的奥义书7/11", page = 31, quest_name = "凯的奥义书", quest_step = 7, quest_total = 11, event_id = 0u, map_id = 542u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{1419}, clear_flags = new List<int>{1420}, complete_flag = 1419 });
                list.Add(new SideEntry { name = "凯的奥义书8/11", page = 31, quest_name = "凯的奥义书", quest_step = 8, quest_total = 11, event_id = 0u, map_id = 580u, x = -1180f, y = -232f, z = 3250f, angle = 0f, set_flags = new List<int>{1421,1427}, clear_flags = new List<int>{1422,1427}, complete_flag = 1427 });
                list.Add(new SideEntry { name = "凯的奥义书9/11", page = 31, quest_name = "凯的奥义书", quest_step = 9, quest_total = 11, event_id = 0u, map_id = 580u, x = -1180f, y = -232f, z = 3250f, angle = 0f, set_flags = new List<int>{1421,1422,1427}, clear_flags = new List<int>{1427}, complete_flag = 1427 });
                list.Add(new SideEntry { name = "凯的奥义书10/11", page = 31, quest_name = "凯的奥义书", quest_step = 10, quest_total = 11, event_id = 0u, map_id = 73u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{1423}, clear_flags = new List<int>{1424}, complete_flag = 1423 });
                list.Add(new SideEntry { name = "凯的奥义书11/11", page = 31, quest_name = "凯的奥义书", quest_step = 11, quest_total = 11, event_id = 0u, map_id = 0u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{}, clear_flags = new List<int>{}, complete_flag = 0 });
                list.Add(new SideEntry { name = "克己1/3", page = 31, quest_name = "克己", quest_step = 1, quest_total = 3, event_id = 3033999u, map_id = 580u, x = -1745f, y = 11f, z = -13f, angle = 0f, set_flags = new List<int>{}, clear_flags = new List<int>{1426,1427}, complete_flag = 0 });
                list.Add(new SideEntry { name = "克己2/3", page = 31, quest_name = "克己", quest_step = 2, quest_total = 3, event_id = 4034000u, map_id = 548u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{1427,1693}, clear_flags = new List<int>{1428}, complete_flag = 1693 });
                list.Add(new SideEntry { name = "克己3/3", page = 31, quest_name = "克己", quest_step = 3, quest_total = 3, event_id = 4035000u, map_id = 229u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{1428}, clear_flags = new List<int>{1429}, complete_flag = 1428 });
                list.Add(new SideEntry { name = "漆黑之钥", page = 31, quest_name = "漆黑之钥", quest_step = 0, quest_total = 0, event_id = 3033000u, map_id = 581u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{}, clear_flags = new List<int>{1439}, complete_flag = 0 });
                _entries[31] = list;
            }
            {
                var list = new List<SideEntry>();
                list.Add(new SideEntry { name = "小恶魔", page = 32, quest_name = "小恶魔", quest_step = 0, quest_total = 0, event_id = 4038270u, map_id = 141u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{}, clear_flags = new List<int>{1625,1440}, complete_flag = 0 });
                list.Add(new SideEntry { name = "予兆", page = 32, quest_name = "予兆", quest_step = 0, quest_total = 0, event_id = 0u, map_id = 0u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{}, clear_flags = new List<int>{}, complete_flag = 0 });
                list.Add(new SideEntry { name = "反省", page = 32, quest_name = "反省", quest_step = 0, quest_total = 0, event_id = 4035000u, map_id = 622u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{1413}, clear_flags = new List<int>{1648,1472}, complete_flag = 1413 });
                list.Add(new SideEntry { name = "凯的宝剑1/3", page = 32, quest_name = "凯的宝剑", quest_step = 1, quest_total = 3, event_id = 1008000u, map_id = 98u, x = -347f, y = 50f, z = -10f, angle = 180f, set_flags = new List<int>{1011,1414,1789}, clear_flags = new List<int>{1604}, complete_flag = 1789 });
                list.Add(new SideEntry { name = "凯的宝剑2/3", page = 32, quest_name = "凯的宝剑", quest_step = 2, quest_total = 3, event_id = 4034000u, map_id = 98u, x = -347f, y = 50f, z = -10f, angle = 180f, set_flags = new List<int>{1604}, clear_flags = new List<int>{1605}, complete_flag = 1604 });
                list.Add(new SideEntry { name = "凯的宝剑3/3", page = 32, quest_name = "凯的宝剑", quest_step = 3, quest_total = 3, event_id = 4039999u, map_id = 98u, x = -347f, y = 50f, z = -10f, angle = 180f, set_flags = new List<int>{1605}, clear_flags = new List<int>{1606}, complete_flag = 1605 });
                list.Add(new SideEntry { name = "spa1/4", page = 32, quest_name = "spa", quest_step = 1, quest_total = 4, event_id = 4034000u, map_id = 529u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{1692}, clear_flags = new List<int>{1693,1694}, complete_flag = 1692 });
                list.Add(new SideEntry { name = "spa2/4", page = 32, quest_name = "spa", quest_step = 2, quest_total = 4, event_id = 4034000u, map_id = 540u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{1692}, clear_flags = new List<int>{1693,1694}, complete_flag = 1692 });
                list.Add(new SideEntry { name = "spa3/4", page = 32, quest_name = "spa", quest_step = 3, quest_total = 4, event_id = 4034000u, map_id = 540u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{1692,1693}, clear_flags = new List<int>{1694}, complete_flag = 1693 });
                _entries[32] = list;
            }
            {
                var list = new List<SideEntry>();
                list.Add(new SideEntry { name = "spa4/4", page = 33, quest_name = "spa", quest_step = 4, quest_total = 4, event_id = 4034000u, map_id = 540u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{1692,1693,1694}, clear_flags = new List<int>{}, complete_flag = 1694 });
                list.Add(new SideEntry { name = "诺瓦尔粉丝俱乐部3/3", page = 33, quest_name = "诺瓦尔粉丝俱乐部", quest_step = 3, quest_total = 3, event_id = 1011080u, map_id = 466u, x = 425f, y = 0f, z = -163f, angle = 140f, set_flags = new List<int>{1724}, clear_flags = new List<int>{1726}, complete_flag = 1724 });
                list.Add(new SideEntry { name = "缇娅和梵的事其１", page = 33, quest_name = "缇娅和梵的事其１", quest_step = 0, quest_total = 0, event_id = 4034000u, map_id = 617u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{}, clear_flags = new List<int>{1410}, complete_flag = 0 });
                list.Add(new SideEntry { name = "缇娅和梵的事其２", page = 33, quest_name = "缇娅和梵的事其２", quest_step = 0, quest_total = 0, event_id = 4035000u, map_id = 622u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{1412}, clear_flags = new List<int>{1413}, complete_flag = 1412 });
                list.Add(new SideEntry { name = "蘑菇之路2", page = 33, quest_name = "蘑菇之路2", quest_step = 0, quest_total = 0, event_id = 4035000u, map_id = 346u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{1213}, clear_flags = new List<int>{1214,1215,1216,1217,1218,1219,1220,1221,1222,1223,1225,1224,1226}, complete_flag = 1213 });
                list.Add(new SideEntry { name = "蘑菇之路3", page = 33, quest_name = "蘑菇之路3", quest_step = 0, quest_total = 0, event_id = 0u, map_id = 98u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{1223}, clear_flags = new List<int>{1226}, complete_flag = 1223 });
                list.Add(new SideEntry { name = "超振动特训1/4", page = 33, quest_name = "超振动特训", quest_step = 1, quest_total = 4, event_id = 2016999u, map_id = 139u, x = 568f, y = 0f, z = -610f, angle = 130f, set_flags = new List<int>{}, clear_flags = new List<int>{1227,1228,1229,1230}, complete_flag = 0 });
                list.Add(new SideEntry { name = "超振动特训2/4", page = 33, quest_name = "超振动特训", quest_step = 2, quest_total = 4, event_id = 2021999u, map_id = 374u, x = 1100f, y = 435f, z = -1940f, angle = 90f, set_flags = new List<int>{1230}, clear_flags = new List<int>{1231,1232,1233,1234}, complete_flag = 1230 });
                list.Add(new SideEntry { name = "超振动特训3/4", page = 33, quest_name = "超振动特训", quest_step = 3, quest_total = 4, event_id = 3025090u, map_id = 139u, x = 568f, y = 0f, z = -610f, angle = 130f, set_flags = new List<int>{1234}, clear_flags = new List<int>{1235,1236,1237,1238}, complete_flag = 1234 });
                _entries[33] = list;
            }
            {
                var list = new List<SideEntry>();
                list.Add(new SideEntry { name = "超振动特训4/4", page = 34, quest_name = "超振动特训", quest_step = 4, quest_total = 4, event_id = 3033999u, map_id = 374u, x = 1100f, y = 435f, z = -1940f, angle = 90f, set_flags = new List<int>{1238}, clear_flags = new List<int>{1239,1240,1241,1242}, complete_flag = 1238 });
                list.Add(new SideEntry { name = "阿尼丝猫人", page = 34, quest_name = "阿尼丝猫人", quest_step = 0, quest_total = 0, event_id = 0u, map_id = 430u, x = -1804f, y = 1f, z = -1292f, angle = 105f, set_flags = new List<int>{}, clear_flags = new List<int>{1243}, complete_flag = 0 });
                list.Add(new SideEntry { name = "深渊战士", page = 34, quest_name = "深渊战士", quest_step = 0, quest_total = 0, event_id = 4037000u, map_id = 595u, x = -122f, y = 0f, z = -95f, angle = 120f, set_flags = new List<int>{2013}, clear_flags = new List<int>{}, complete_flag = 0 });
                list.Add(new SideEntry { name = "娜塔莉亚奥义1", page = 34, quest_name = "娜塔莉亚奥义1", quest_step = 0, quest_total = 0, event_id = 2014999u, map_id = 396u, x = -305f, y = 2f, z = 312f, angle = 270f, set_flags = new List<int>{}, clear_flags = new List<int>{1250,1251,1252,1253}, complete_flag = 0 });
                list.Add(new SideEntry { name = "娜塔莉亚奥义2", page = 34, quest_name = "娜塔莉亚奥义2", quest_step = 0, quest_total = 0, event_id = 2022999u, map_id = 206u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{1251}, clear_flags = new List<int>{1252}, complete_flag = 1251 });
                list.Add(new SideEntry { name = "娜塔莉亚奥义3", page = 34, quest_name = "娜塔莉亚奥义3", quest_step = 0, quest_total = 0, event_id = 4035999u, map_id = 206u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{1252}, clear_flags = new List<int>{1253}, complete_flag = 1252 });
                list.Add(new SideEntry { name = "卢克奥义（瞬迅剑）", page = 34, quest_name = "卢克奥义（瞬迅剑）", quest_step = 0, quest_total = 0, event_id = 1005100u, map_id = 467u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{1003}, clear_flags = new List<int>{1279,1283,1280,1284,1281,1285,1282,1286}, complete_flag = 0 });
                list.Add(new SideEntry { name = "齐格尔长老迷你游戏", page = 34, quest_name = "齐格尔长老迷你游戏", quest_step = 0, quest_total = 0, event_id = 2014000u, map_id = 426u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{}, clear_flags = new List<int>{}, complete_flag = 0 });
                list.Add(new SideEntry { name = "全情节概述设置", page = 34, quest_name = "全情节概述设置", quest_step = 0, quest_total = 0, event_id = 4039200u, map_id = 0u, x = 0f, y = 0f, z = 0f, angle = 0f, set_flags = new List<int>{}, clear_flags = new List<int>{}, complete_flag = 0 });
                _entries[34] = list;
            }
            {
                var list = new List<SideEntry>();
                list.Add(new SideEntry { name = "诺瓦尔3", page = 35, quest_name = "诺瓦尔3", quest_step = 0, quest_total = 0, event_id = 1011080u, map_id = 466u, x = 287f, y = 0f, z = 149f, angle = 0f, set_flags = new List<int>{1530,1724}, clear_flags = new List<int>{1725,1726}, complete_flag = 1724 });
                _entries[35] = list;
            }
        }
    }
}